-- İrsaliye – Fatura Sistemi · tek dosyalık kurulum
--
-- Bu dosyayı Supabase panelinde SQL Editor'e yapıştırıp çalıştırın.
--
-- BOŞ bir veritabanında BİR KEZ çalıştırılmak üzere üretilmiştir. İkinci kez
-- çalıştırırsanız şema kısmı "already exists" hatası verip durur; veri
-- değişmez, zararı olmaz. Tohum kayıtları ayrıca ON CONFLICT DO NOTHING ile
-- korunur.
--
-- Üreten: npm run db:sql  (prisma/sql-uret.ts)
-- Şema değiştiğinde bu dosyayı yeniden üretin.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "Rol" AS ENUM ('SANTIYE', 'IDARI_MUDUR', 'MERKEZ', 'YONETICI');

-- CreateEnum
CREATE TYPE "FaturaDurum" AS ENUM ('YENI', 'ESLESTI', 'IMZALANDI', 'REDDEDILDI', 'MERKEZ_ONAYLI', 'GONDERILDI', 'IPTAL');

-- CreateEnum
CREATE TYPE "OnayTip" AS ENUM ('IMZA', 'RED', 'MERKEZ_ONAY', 'MERKEZ_RED');

-- CreateTable
CREATE TABLE "Kullanici" (
    "id" SERIAL NOT NULL,
    "eposta" TEXT NOT NULL,
    "ad" TEXT NOT NULL,
    "parolaHash" TEXT NOT NULL,
    "rol" "Rol" NOT NULL,
    "aktif" BOOLEAN NOT NULL DEFAULT true,
    "olusturmaT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Kullanici_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Firma" (
    "id" SERIAL NOT NULL,
    "ad" TEXT NOT NULL,
    "vergiNo" TEXT,
    "telefon" TEXT,
    "not" TEXT,
    "aktif" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "Firma_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Secenek" (
    "id" SERIAL NOT NULL,
    "grup" TEXT NOT NULL,
    "deger" TEXT NOT NULL,
    "sira" INTEGER NOT NULL DEFAULT 0,
    "aktif" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "Secenek_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Belge" (
    "id" SERIAL NOT NULL,
    "ad" TEXT NOT NULL,
    "yol" TEXT NOT NULL,
    "mimeTur" TEXT NOT NULL,
    "boyut" INTEGER NOT NULL,
    "sha256" TEXT NOT NULL,
    "yukleyenId" INTEGER,
    "olusturmaT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Belge_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Irsaliye" (
    "id" SERIAL NOT NULL,
    "no" TEXT,
    "tarih" DATE NOT NULL,
    "firmaId" INTEGER NOT NULL,
    "cari" TEXT,
    "aciklama" TEXT,
    "belgeId" INTEGER,
    "girenId" INTEGER,
    "olusturmaT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "guncellemeT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Irsaliye_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "IrsaliyeKalem" (
    "id" SERIAL NOT NULL,
    "irsaliyeId" INTEGER NOT NULL,
    "sira" INTEGER NOT NULL DEFAULT 0,
    "kategori" TEXT,
    "tur" TEXT,
    "malzeme" TEXT NOT NULL,
    "miktar" DECIMAL(14,3) NOT NULL,
    "birim" TEXT NOT NULL,
    "birimFiyat" DECIMAL(14,2),
    "toplam" DECIMAL(14,2),

    CONSTRAINT "IrsaliyeKalem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Fatura" (
    "id" SERIAL NOT NULL,
    "no" TEXT NOT NULL,
    "tarih" DATE NOT NULL,
    "firmaId" INTEGER NOT NULL,
    "tutar" DECIMAL(14,2) NOT NULL,
    "kategori" TEXT,
    "aciklama" TEXT,
    "odeme" TEXT,
    "irsaliyesiz" BOOLEAN NOT NULL DEFAULT false,
    "durum" "FaturaDurum" NOT NULL DEFAULT 'YENI',
    "belgeId" INTEGER,
    "girenId" INTEGER,
    "gonderimId" INTEGER,
    "olusturmaT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "guncellemeT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Fatura_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Eslesme" (
    "id" SERIAL NOT NULL,
    "faturaId" INTEGER NOT NULL,
    "irsaliyeId" INTEGER NOT NULL,
    "kuranId" INTEGER,
    "not" TEXT,
    "olusturmaT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Eslesme_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Onay" (
    "id" SERIAL NOT NULL,
    "faturaId" INTEGER NOT NULL,
    "tip" "OnayTip" NOT NULL,
    "kullaniciId" INTEGER,
    "kullaniciAd" TEXT NOT NULL,
    "kullaniciEposta" TEXT NOT NULL,
    "kullaniciRol" "Rol" NOT NULL,
    "tarih" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ip" TEXT,
    "tarayici" TEXT,
    "ozet" TEXT NOT NULL,
    "anlik" JSONB NOT NULL,
    "not" TEXT,

    CONSTRAINT "Onay_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Gonderim" (
    "id" SERIAL NOT NULL,
    "no" TEXT NOT NULL,
    "tarih" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "musavir" TEXT,
    "not" TEXT,
    "olusturanId" INTEGER,

    CONSTRAINT "Gonderim_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Islem" (
    "id" SERIAL NOT NULL,
    "kullaniciId" INTEGER,
    "tur" TEXT NOT NULL,
    "nesne" TEXT NOT NULL,
    "nesneId" INTEGER,
    "detay" JSONB,
    "ip" TEXT,
    "tarih" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Islem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Ayar" (
    "anahtar" TEXT NOT NULL,
    "deger" TEXT NOT NULL,

    CONSTRAINT "Ayar_pkey" PRIMARY KEY ("anahtar")
);

-- CreateIndex
CREATE UNIQUE INDEX "Kullanici_eposta_key" ON "Kullanici"("eposta");

-- CreateIndex
CREATE UNIQUE INDEX "Firma_ad_key" ON "Firma"("ad");

-- CreateIndex
CREATE INDEX "Secenek_grup_aktif_idx" ON "Secenek"("grup", "aktif");

-- CreateIndex
CREATE UNIQUE INDEX "Secenek_grup_deger_key" ON "Secenek"("grup", "deger");

-- CreateIndex
CREATE INDEX "Irsaliye_tarih_idx" ON "Irsaliye"("tarih");

-- CreateIndex
CREATE INDEX "Irsaliye_firmaId_idx" ON "Irsaliye"("firmaId");

-- CreateIndex
CREATE UNIQUE INDEX "Irsaliye_firmaId_no_key" ON "Irsaliye"("firmaId", "no");

-- CreateIndex
CREATE INDEX "IrsaliyeKalem_irsaliyeId_idx" ON "IrsaliyeKalem"("irsaliyeId");

-- CreateIndex
CREATE INDEX "Fatura_durum_idx" ON "Fatura"("durum");

-- CreateIndex
CREATE INDEX "Fatura_tarih_idx" ON "Fatura"("tarih");

-- CreateIndex
CREATE UNIQUE INDEX "Fatura_firmaId_no_key" ON "Fatura"("firmaId", "no");

-- CreateIndex
CREATE INDEX "Eslesme_irsaliyeId_idx" ON "Eslesme"("irsaliyeId");

-- CreateIndex
CREATE UNIQUE INDEX "Eslesme_faturaId_irsaliyeId_key" ON "Eslesme"("faturaId", "irsaliyeId");

-- CreateIndex
CREATE INDEX "Onay_faturaId_idx" ON "Onay"("faturaId");

-- CreateIndex
CREATE INDEX "Onay_tip_idx" ON "Onay"("tip");

-- CreateIndex
CREATE UNIQUE INDEX "Gonderim_no_key" ON "Gonderim"("no");

-- CreateIndex
CREATE INDEX "Islem_tarih_idx" ON "Islem"("tarih");

-- CreateIndex
CREATE INDEX "Islem_nesne_nesneId_idx" ON "Islem"("nesne", "nesneId");

-- AddForeignKey
ALTER TABLE "Belge" ADD CONSTRAINT "Belge_yukleyenId_fkey" FOREIGN KEY ("yukleyenId") REFERENCES "Kullanici"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Irsaliye" ADD CONSTRAINT "Irsaliye_firmaId_fkey" FOREIGN KEY ("firmaId") REFERENCES "Firma"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Irsaliye" ADD CONSTRAINT "Irsaliye_belgeId_fkey" FOREIGN KEY ("belgeId") REFERENCES "Belge"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Irsaliye" ADD CONSTRAINT "Irsaliye_girenId_fkey" FOREIGN KEY ("girenId") REFERENCES "Kullanici"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IrsaliyeKalem" ADD CONSTRAINT "IrsaliyeKalem_irsaliyeId_fkey" FOREIGN KEY ("irsaliyeId") REFERENCES "Irsaliye"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Fatura" ADD CONSTRAINT "Fatura_firmaId_fkey" FOREIGN KEY ("firmaId") REFERENCES "Firma"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Fatura" ADD CONSTRAINT "Fatura_belgeId_fkey" FOREIGN KEY ("belgeId") REFERENCES "Belge"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Fatura" ADD CONSTRAINT "Fatura_girenId_fkey" FOREIGN KEY ("girenId") REFERENCES "Kullanici"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Fatura" ADD CONSTRAINT "Fatura_gonderimId_fkey" FOREIGN KEY ("gonderimId") REFERENCES "Gonderim"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Eslesme" ADD CONSTRAINT "Eslesme_faturaId_fkey" FOREIGN KEY ("faturaId") REFERENCES "Fatura"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Eslesme" ADD CONSTRAINT "Eslesme_irsaliyeId_fkey" FOREIGN KEY ("irsaliyeId") REFERENCES "Irsaliye"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Eslesme" ADD CONSTRAINT "Eslesme_kuranId_fkey" FOREIGN KEY ("kuranId") REFERENCES "Kullanici"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Onay" ADD CONSTRAINT "Onay_faturaId_fkey" FOREIGN KEY ("faturaId") REFERENCES "Fatura"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Onay" ADD CONSTRAINT "Onay_kullaniciId_fkey" FOREIGN KEY ("kullaniciId") REFERENCES "Kullanici"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Gonderim" ADD CONSTRAINT "Gonderim_olusturanId_fkey" FOREIGN KEY ("olusturanId") REFERENCES "Kullanici"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Islem" ADD CONSTRAINT "Islem_kullaniciId_fkey" FOREIGN KEY ("kullaniciId") REFERENCES "Kullanici"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================
--  TOHUM VERİSİ
-- ============================================================

-- 192 firma
INSERT INTO "Firma" ("ad") VALUES
  ('ADEM KUDAL'),
  ('AK İŞ GRUP'),
  ('AKDEMİR KARDEŞLER'),
  ('AKPNR TEKNİK'),
  ('ALİ ALOĞLU'),
  ('ALİ ASLAN'),
  ('ALİ CANGÜL'),
  ('ALİ OSMAN KOCA'),
  ('ALİ TANSIK'),
  ('ANF BOYA'),
  ('ANTİPEST İLAÇLAMA'),
  ('ARINTEK HIRDAVAT'),
  ('ARK TESİSAT'),
  ('ARSLANOĞLU'),
  ('ARSLANOĞLU YAPI'),
  ('ARTAŞ'),
  ('ARŞAŞ PETROL'),
  ('ATEM NAKLİYAT'),
  ('AYDIN ŞAHİN'),
  ('AYK YAPI'),
  ('AYKAR LABORATUVAR'),
  ('AYTEKİN KABAKCI'),
  ('BAHRİ BİLGE'),
  ('BAUHAUS'),
  ('BAŞKENT GRUP'),
  ('BAŞOL YAPI'),
  ('BİM'),
  ('BİRLİK BETON'),
  ('BOŞ'),
  ('BYB ANDEZİT'),
  ('BÜNYAMİN OLĞUN'),
  ('CAN OFİS KIRTASİYE'),
  ('CANGÜL'),
  ('CANLAR BORU'),
  ('CANYURT'),
  ('CANYURT HIRDAVAT'),
  ('CESA'),
  ('CİTY GROSS'),
  ('CMU RESTORAN'),
  ('CUMA ALİ MADEN'),
  ('DERYA HIRDAVAT'),
  ('DESA YAPI'),
  ('DEVKAR TAŞIMACILIK'),
  ('DMC SERAMİK'),
  ('DNZ GRUP'),
  ('DOST ELEKTRİK'),
  ('DOĞAN DENİZ'),
  ('DOĞANSU PVC'),
  ('DSM GRUP'),
  ('DÖNÜŞÜM İŞ SAĞLIĞI'),
  ('EKŞİOĞLU'),
  ('ELİT MUTLU YEMEK'),
  ('ELMALI İNŞ. MALZEMELERİ.'),
  ('ELMALI ŞANTİYE'),
  ('EMRE ALTUNSARAY'),
  ('EMRELER HAFRİYAT'),
  ('ENGİN ASLAN'),
  ('ENGİN GRUP'),
  ('ERAY ÇELİK'),
  ('ERDAL MİTHAT'),
  ('EREN KUM'),
  ('ERENKUM'),
  ('ERHAN AVCİL'),
  ('ERİŞSAN'),
  ('ERSAN TEKNİK'),
  ('FİSCHER'),
  ('FİSCHER METAL'),
  ('FN TEKNOLOJİ'),
  ('FYS GRUP'),
  ('GAZİ DEMİRHAN'),
  ('GENÇ İŞ'),
  ('GERSAN ELEKTRİK'),
  ('GÖKHAN GÜLGER'),
  ('GÖRKEM DEKORASYON'),
  ('GÜNEY KAYALAR'),
  ('HAKSA YAPI'),
  ('HASAN GÜNEY'),
  ('HASAN ŞAHİN'),
  ('HAZALLAR'),
  ('HİDROSOFT'),
  ('HT HAKAN'),
  ('ILGAZ DORUK'),
  ('İBRAHİM AKSOY'),
  ('İLHAN AVCİL'),
  ('İLHAN AYGAN'),
  ('İLYAS PINAR'),
  ('İNTER İZOLASYON'),
  ('İSMAİL ASAN'),
  ('İSMAİLOĞLU ORMAN'),
  ('İSMAK ENERJİ'),
  ('İSMET KAPLANER'),
  ('İŞTEK'),
  ('İŞTEK İNŞAAT'),
  ('KADİR MİMARLIK'),
  ('KAMAR DAĞITIM'),
  ('KARADERE MADENCİLİK'),
  ('KEREMHAN YAMAN'),
  ('KMC ELEKTRİK'),
  ('KNAUF'),
  ('KOCMAK'),
  ('KOR DEMİR'),
  ('KORU KARDEŞLER'),
  ('KOÇ ANTİK'),
  ('KOÇKUM'),
  ('KULE GRUP'),
  ('KULE PETROL'),
  ('KUZEY KONTEYNER'),
  ('LEVENT ÇÖKLÜ'),
  ('LİVA PASTANESİ'),
  ('M PRATİK'),
  ('MAK GRUP'),
  ('MALATYA ŞANTİYESİ'),
  ('MEGA YALITIM'),
  ('MEGAS YAPI'),
  ('MEHMET DENİZ'),
  ('MEHMET FATİH POLAT'),
  ('MEHMET KARABULUT'),
  ('MEHMET YÜCEL'),
  ('MENDUH TAŞ'),
  ('MESUT HARMAN'),
  ('METEHAN İSKELE'),
  ('METİN KELEŞ'),
  ('MİLAT HARİTA'),
  ('MK ASİL KİMYA'),
  ('MURAT SAÇAK'),
  ('MURAT YAĞCI'),
  ('MUSTAFA ASLAN'),
  ('MUSTAFA ÖMÜR DOĞAN'),
  ('NK NUR'),
  ('NK NUR YAPI'),
  ('NOVA GRUP'),
  ('NT MÜŞAVİRLİK'),
  ('NURİ KARADENİZ'),
  ('OMEGA MAKİNA'),
  ('PAKEL İSKELE'),
  ('PEK-ER KAPI'),
  ('PERSAN YAPI'),
  ('RAVABER YALITIM'),
  ('RİTİM YAPI'),
  ('SAFA CEYLAN'),
  ('SARGIN HAZIR BETON'),
  ('SEFA SU'),
  ('SELİM DAĞDELENER'),
  ('SELÇUK EKŞİOĞLU'),
  ('SEMBOL ELEKTRİK'),
  ('SERCAN ÖZTEKİN'),
  ('SERDAR ÖZYURT'),
  ('SİF İŞ MAKİNA'),
  ('STS ELEKTRİK'),
  ('STT GAZBETON'),
  ('SY ANKARA BETON'),
  ('SY ANKARA HAZIR BETON'),
  ('SYS İSKELE'),
  ('SÖNMEZ KONTEYNER'),
  ('TANER YEMEK'),
  ('TB GRUP SU'),
  ('TEKNOSİS MEKANİK'),
  ('TETPAN ELEKTRİK'),
  ('TEZCAN'),
  ('TOPALOĞULLARI SU'),
  ('TREND YANGIN'),
  ('TUNA PANO'),
  ('UMUD GİYİM'),
  ('UNİVERSAL OTOMASYON'),
  ('UĞURAL'),
  ('VATAN BİLGİSAYAR'),
  ('Y2 İNŞAAT'),
  ('YAVUZ SİVİŞ'),
  ('YETVEN'),
  ('YETVEN ELEKTRİK'),
  ('YEŞİL HAFRİYAT'),
  ('YUSUF ÇELİK'),
  ('YUSUF ÖZTÜRK'),
  ('YÜKSEL KIRTASİYE'),
  ('ZEKERİYE ERTÜRK'),
  ('ZETA ÇELİK'),
  ('ZETAS END.'),
  ('ZİRVE TEL ÖRGÜ'),
  ('ZÜLKARNEYN ATİLA'),
  ('ÇEVİK TİCARET'),
  ('ÇINARLAR GRUP'),
  ('ÇİZEL-SAMUR-TÜRKAY'),
  ('ÖLMEZ KURTARMA'),
  ('ÖNCEL TEKNİK'),
  ('ÖZ ALDEMİR'),
  ('ÖZAYLAR EL'),
  ('ÖZAYLAR HIRDAVAT'),
  ('ÖZAYLAR YEMEK'),
  ('ÖZKAN KIRIKÇI'),
  ('ÖZKAY CNC'),
  ('ÜMİT ÖZKAYA'),
  ('ŞERİFE ALTINBAŞ')
ON CONFLICT ("ad") DO NOTHING;

-- 1303 açılır liste değeri
INSERT INTO "Secenek" ("grup", "deger", "sira") VALUES
  ('BIRIM', 'ADET', 0),
  ('BIRIM', 'M', 1),
  ('BIRIM', 'KG', 2),
  ('BIRIM', 'PAKET', 3),
  ('BIRIM', 'PALET', 4),
  ('BIRIM', 'M3', 5),
  ('BIRIM', 'TON', 6),
  ('BIRIM', 'M2', 7),
  ('BIRIM', 'SET', 8),
  ('BIRIM', 'LİTRE', 9),
  ('CARI', 'ÇİZEL', 0),
  ('CARI', 'GENEL - KESİNTİ', 1),
  ('CARI', 'HAYRİ FİDAN', 2),
  ('CARI', 'M.ŞİRİN MARAL', 3),
  ('CARI', 'ARS GRUP', 4),
  ('CARI', 'MEHMET TUĞAL', 5),
  ('IRSALIYE_KATEGORI', 'DEMİRBAŞ', 0),
  ('IRSALIYE_KATEGORI', 'İSG', 1),
  ('IRSALIYE_KATEGORI', 'SARF', 2),
  ('IRSALIYE_KATEGORI', 'ARAÇ', 3),
  ('IRSALIYE_KATEGORI', 'YAPI MALZEMESİ', 4),
  ('IRSALIYE_KATEGORI', 'ELEKTRİK - MEKANİK', 5),
  ('IRSALIYE_KATEGORI', 'ELEKTRONİK ALET', 6),
  ('TUR', 'AHŞAP PALET', 0),
  ('TUR', 'ALÇI KÖŞE PROFİLİ', 1),
  ('TUR', 'ALÇI SIVA', 2),
  ('TUR', 'BAĞ TELİ', 3),
  ('TUR', 'BARET', 4),
  ('TUR', 'BETON', 5),
  ('TUR', 'BETON ASTARI', 6),
  ('TUR', 'BOYA', 7),
  ('TUR', 'BRÜT BETON ASTARI', 8),
  ('TUR', 'ÇATI BAĞLANTISI', 9),
  ('TUR', 'ÇELİK HASIR', 10),
  ('TUR', 'ÇİMENTO', 11),
  ('TUR', 'ÇUVAL', 12),
  ('TUR', 'DEMİR', 13),
  ('TUR', 'DUŞ KANALI', 14),
  ('TUR', 'DUVAR TAŞI', 15),
  ('TUR', 'EL ARABASI', 16),
  ('TUR', 'EPOKSİ', 17),
  ('TUR', 'EPS', 18),
  ('TUR', 'GAZBETON', 19),
  ('TUR', 'GAZBETON YAPIŞTIRICISI', 20),
  ('TUR', 'ISPATULA', 21),
  ('TUR', 'İŞ AYAKKABISI', 22),
  ('TUR', 'İŞ ELDİVENİ', 23),
  ('TUR', 'KABLO - 3*15 TTR', 24),
  ('TUR', 'KABLO - 3*25 TTR', 25),
  ('TUR', 'KERESTE', 26),
  ('TUR', 'KIRICI - DELİCİ UÇ', 27),
  ('TUR', 'KİREÇ', 28),
  ('TUR', 'KİREMİT', 29),
  ('TUR', 'KONTEYNER', 30),
  ('TUR', 'KORUYUCU GÖZLÜK', 31),
  ('TUR', 'KUM', 32),
  ('TUR', 'MAKET BIÇAĞI', 33),
  ('TUR', 'MANTOLAMA FİLESİ', 34),
  ('TUR', 'MANTOLAMA SIVASI', 35),
  ('TUR', 'MANTOLAMA YAPIŞTIRICISI', 36),
  ('TUR', 'MEMBRAN', 37),
  ('TUR', 'MİNERAL SIVA', 38),
  ('TUR', 'NEVRESİM', 39),
  ('TUR', 'POLİÜRETAN KÖPÜK', 40),
  ('TUR', 'SATEN ALÇI', 41),
  ('TUR', 'SERAMİK', 42),
  ('TUR', 'SERAMİK YAPIŞTIRICISI', 43),
  ('TUR', 'SIVA FİLESİ', 44),
  ('TUR', 'SIVAMATİK', 45),
  ('TUR', 'SİLİKON', 46),
  ('TUR', 'SPİRAL TAŞI', 47),
  ('TUR', 'SU İZOLASYONU', 48),
  ('TUR', 'TAMİR HARCI', 49),
  ('TUR', 'TAŞYÜNÜ', 50),
  ('TUR', 'XPS', 51),
  ('TUR', 'YAKIT', 52),
  ('TUR', 'YATAK SÜNGERİ', 53),
  ('TUR', 'YELEK', 54),
  ('MALZEME', '1 1/2" SOMUNLU KELEPCE-75-', 0),
  ('MALZEME', '1 1/4 " SOMUNLU KELEPCE -100-', 1),
  ('MALZEME', '1 1/4" GALVANİZ BORU', 2),
  ('MALZEME', '1" SOMUNLU KELEРСE -150-', 3),
  ('MALZEME', '1" TRİFONLU KELEPCE KISA', 4),
  ('MALZEME', '1/2 ALTI KÖŞE LOKMA ANAHTAR TAKIMI - 24 PARÇA', 5),
  ('MALZEME', '1/2 MANŞONLU HAVA TÜPÜ - 5 LT', 6),
  ('MALZEME', '1/2'''' SİYAH ÇELİK MANŞON', 7),
  ('MALZEME', '1/2" R1-R2 SOKET', 8),
  ('MALZEME', '1/2"-1/2" R 90 REKOR', 9),
  ('MALZEME', '1/2"-1/2" R ERKEK REKOR', 10),
  ('MALZEME', '10 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım)', 11),
  ('MALZEME', '11 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım)', 12),
  ('MALZEME', '11/2" TRİFONLU KELEPÇE KISA', 13),
  ('MALZEME', '11/4" TRİFONLU KELEPÇE KISA', 14),
  ('MALZEME', '110 Kalde 32 Tapa', 15),
  ('MALZEME', '110 Kalde Atıksu Dirsek (45°)', 16),
  ('MALZEME', '110 Kalde Atıksu Dirsek (87°)', 17),
  ('MALZEME', '110 Kalde Atiksu S (87°)', 18),
  ('MALZEME', '110/75 Kalde Atıksu Redüksiyon', 19),
  ('MALZEME', '110X1000 Kalde Tip1 PVC U Boru B Tipi', 20),
  ('MALZEME', '110X110  Kalde  Kalde Atıksu Çift Çatal (45°)', 21),
  ('MALZEME', '110X110 Kalde Atıksu Tek Çatal (45°)', 22),
  ('MALZEME', '110X2000 Kalde Tip1 PVC U Boru B Tipi', 23),
  ('MALZEME', '110X3000 Kalde Tip1 PVC U Boru B Tipi', 24),
  ('MALZEME', '110X50 Kalde Atıksu Redüksiyon', 25),
  ('MALZEME', '110X50 Kalde Atıksu Tek Çatal (45°)', 26),
  ('MALZEME', '110X500 Kalde Tip1 PVC U Boru B Tipi', 27),
  ('MALZEME', '110X75 Kalde Atıksu Tek Çatal (45°)', 28),
  ('MALZEME', '12 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım)', 29),
  ('MALZEME', '12"x5 MM SİYAH DÜZ UÇLU BORU', 30),
  ('MALZEME', '125 Kalde Atıksu Dirsek (45°)', 31),
  ('MALZEME', '125/110 Kalde Atıksu Redüksiyon', 32),
  ('MALZEME', '125X1000 Kalde Tip1 PVC U Boru B Tipi', 33),
  ('MALZEME', '125X110 Kalde Atıksu Tek Çatal (45°)', 34),
  ('MALZEME', '125X125 Kalde Atıksu Tek Çatal (45°)', 35),
  ('MALZEME', '125X3000 Kalde Tip1 PVC U Boru B Tipi', 36),
  ('MALZEME', '125X500 Kalde Tip1 PVC U Boru B Tipi', 37),
  ('MALZEME', '16 MM SKP PABUÇ', 38),
  ('MALZEME', '16X16 KABLO KANALI YAPIŞKANLI', 39),
  ('MALZEME', '1X10A 6kA B AOS', 40),
  ('MALZEME', '1X16A 6 kA C AOS', 41),
  ('MALZEME', '2 "GALVANİZLİ BORU', 42),
  ('MALZEME', '2 1/2 " SOMUNLU KELEPÇE -40-', 43),
  ('MALZEME', '2 1/2'''' PATENT DİRSEK', 44),
  ('MALZEME', '2 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım)', 45),
  ('MALZEME', '2 MM SEVİYE', 46),
  ('MALZEME', '2 SOMUNLU KELEPÇE -50-', 47),
  ('MALZEME', '2-1/2" BOYALI DÜZ UÇLU BORU', 48),
  ('MALZEME', '2'''' DİREK BAĞLANTI KELEPÇESİ', 49),
  ('MALZEME', '2'''' DİREK TABANI ORTADAN', 50),
  ('MALZEME', '2'''' GALVANİZ DİŞLİ MANŞONLU BORU L=6000mm.', 51),
  ('MALZEME', '2'''' GALVANİZ KUYRUKLU DİRSEK', 52),
  ('MALZEME', '2'''' GALVANİZ NİPEL', 53),
  ('MALZEME', '2'''' YANGIN VANASI', 54),
  ('MALZEME', '2" BOYALI DÜZ UÇLU BORU', 55),
  ('MALZEME', '2" GALVANİZ DİRSEK TD', 56),
  ('MALZEME', '2" GALVANİZ TE TD', 57),
  ('MALZEME', '21/2 GALVANİZ BORU', 58),
  ('MALZEME', '21/2'''' GALVANİZ NİPEL', 59),
  ('MALZEME', '21/2" GALVANİZ DİRSEK TD', 60),
  ('MALZEME', '21/2" GALVANİZ TE TD', 61),
  ('MALZEME', '21/2*2" GALVANİZ REDÜKSİYON TD', 62),
  ('MALZEME', '2x50mm2 TRİFONLU İNİŞ KROŞESİ', 63),
  ('MALZEME', '3" BOYALI DÜZ UÇLU BORU', 64),
  ('MALZEME', '300X225 MOTORLU PROJEKSİYON PERDESİ', 65),
  ('MALZEME', '4" BOYALI DÜZ UÇLU BORU', 66),
  ('MALZEME', '4" GALVANİZ DİŞLİ MANŞONLU BORU', 67),
  ('MALZEME', '4X25 A230V AC TESİSAT KONTAKTÖRÜ', 68),
  ('MALZEME', '4X25A 30mA K.A.K.R', 69),
  ('MALZEME', '5'''' PATENT DİRSEK', 70),
  ('MALZEME', '5" BOYALI DÜZ UÇLU BORU', 71),
  ('MALZEME', '50 Kalde Atıksu Kayar Manşon', 72),
  ('MALZEME', '50mm2 MONO BAKIR İLETKEN', 73),
  ('MALZEME', '6'''' GALVANİZ DİŞLİ MANŞONLU BORU', 74),
  ('MALZEME', '6" BOYALI DÜZ UÇLU BORU', 75),
  ('MALZEME', '8'''' PATENT DİRSEK', 76),
  ('MALZEME', '8" BOYALI DÜZ UÇLU BORU', 77),
  ('MALZEME', '8x5'''' PATENT REDÜKSİYON', 78),
  ('MALZEME', 'AKTİF PARATONER', 79),
  ('MALZEME', 'ALÇI KÖŞE PROFİLİ - BAKLAVA DİLİMLİ 27 MT', 80),
  ('MALZEME', 'ALÇI KÖŞE PROFİLİ - YUVARLAK DELİKLİ 2.7 MT', 81),
  ('MALZEME', 'ALÇI MALASI', 82),
  ('MALZEME', 'ANO ÇITASI - 2.7 MT', 83),
  ('MALZEME', 'ANTİPAS - 3 KG', 84),
  ('MALZEME', 'ANTİPAS TENEKE', 85),
  ('MALZEME', 'ASKI ÇUBUĞU - 60', 86),
  ('MALZEME', 'ASKI MAŞASI', 87),
  ('MALZEME', 'Atıksu Dirsek (45°) - 110 Kalde', 88),
  ('MALZEME', 'Atıksu Tek Çatal (45°) - 110X50 Kalde', 89),
  ('MALZEME', 'BAKIR ELEKTROT BAĞLANTI KLEMENSİ E:2MM', 90),
  ('MALZEME', 'BANYO AYNA TAKIMI', 91),
  ('MALZEME', 'BARET - KIRMIZI', 92),
  ('MALZEME', 'BARET - MAVİ', 93),
  ('MALZEME', 'BETON TOPRAKLAMA ROGARI 400X400X400MM', 94),
  ('MALZEME', 'BEYAZ ALÇI LEVHA - 1.20x2.50', 95),
  ('MALZEME', 'BİĞET FLANŞ - 63', 96),
  ('MALZEME', 'BİĞET FLANŞ - 75', 97),
  ('MALZEME', 'BİĞET FLANŞ - 80', 98),
  ('MALZEME', 'BİTÜM ASTAR - 15KG', 99),
  ('MALZEME', 'BORU TESPİT KROŞESİ', 100),
  ('MALZEME', 'BOSCH GBH 2-26 MATKAP KIRICI DELİCİ', 101),
  ('MALZEME', 'BOSCH GWS 18V-8 1125 MM ÇİFT AKÜLÜ TAŞLAMA MAKİNESİ', 102),
  ('MALZEME', 'BOYA - AQUSTO 2.5LT', 103),
  ('MALZEME', 'BOYA - AQUSTO RG1 2.5 LT', 104),
  ('MALZEME', 'BOYA - İÇ CEPHE 3.5 KG', 105),
  ('MALZEME', 'BOYA - MOMENTO RG1 SİLAN 2.5 LT', 106),
  ('MALZEME', 'BOYA - MOMENTO SİLAN RG2 2.5LT', 107),
  ('MALZEME', 'BOYA - SİLİKONLU DIŞ CEPHE 3.5 KG', 108),
  ('MALZEME', 'BOYA - SİLİKONLU İÇ CEPHE 3.5 KG', 109),
  ('MALZEME', 'BOYA ASTAR - 20 KG', 110),
  ('MALZEME', 'BOYA KARIŞTIRICI - RUBİMİX-8 EASY PRO', 111),
  ('MALZEME', 'BOYA KARIŞTIRICI - SCHEPPACH PM 1400', 112),
  ('MALZEME', 'BOYLER SENSÖRÜ', 113),
  ('MALZEME', 'BRANDA ÇADIR 6X6', 114),
  ('MALZEME', 'BRÜT BETON ASTARI - 12 KG', 115),
  ('MALZEME', 'BRÜT BETON ASTARI - 20 KG', 116),
  ('MALZEME', 'ÇAMAŞIR DETERJANI', 117),
  ('MALZEME', 'ÇATI BAĞLANTISI - I', 118),
  ('MALZEME', 'ÇATI BAĞLANTISI - L', 119),
  ('MALZEME', 'ÇATI BAĞLANTISI - T', 120),
  ('MALZEME', 'ÇATI BAĞLANTISI - Y', 121),
  ('MALZEME', 'ÇAY MAKİNESİ - MİZAN 40', 122),
  ('MALZEME', 'ÇELİK DÜBEL - ASMA TAVAN', 123),
  ('MALZEME', 'ÇELİK HASIR - Q6 MM', 124),
  ('MALZEME', 'ÇIRPI İPİ - 370 MT', 125),
  ('MALZEME', 'ÇIRPI İPİ - BOYALI', 126),
  ('MALZEME', 'ÇİMENTO - 42.5 (50KG)', 127),
  ('MALZEME', 'ÇİVİ - GAZLI TABANCA (1000 ADET)', 128),
  ('MALZEME', 'DB - ANA DAĞITIM PANOSU', 129),
  ('MALZEME', 'DB - İÇ PANO', 130),
  ('MALZEME', 'DB - UPS PANOSU', 131),
  ('MALZEME', 'DEKOR SIVA TEKNESİ', 132),
  ('MALZEME', 'DERZ BANDI - 5CM 90M', 133),
  ('MALZEME', 'DEVRE SİRKÜLASYON POMPASI', 134),
  ('MALZEME', 'DIŞ HAVA SENSÖRÜ', 135),
  ('MALZEME', 'DUŞ KANALI - 40 CM', 136),
  ('MALZEME', 'DUVAR TAŞI', 137),
  ('MALZEME', 'DÜBEL - KAPALI KANCALI M10x120', 138),
  ('MALZEME', 'DÜBEL - M12x110', 139),
  ('MALZEME', 'DÜBEL AÇIK KANCALI M10x115', 140),
  ('MALZEME', 'DÜZ FLANŞ - 125', 141),
  ('MALZEME', 'DÜZ FLANŞ - 200', 142),
  ('MALZEME', 'DÜZ FLANŞ - 50', 143),
  ('MALZEME', 'DÜZ FLANŞ - 65', 144),
  ('MALZEME', 'DÜZ FLANŞ - 80', 145),
  ('MALZEME', 'DÜZ REKOR (1-1/2)', 146),
  ('MALZEME', 'DÜZ REKOR (1)', 147),
  ('MALZEME', 'DÜZ REKOR (2)', 148),
  ('MALZEME', 'E-155 HALAT TUTUCU 16MM', 149),
  ('MALZEME', 'EK MUF - 120MM', 150),
  ('MALZEME', 'EK MUF - 95MM', 151),
  ('MALZEME', 'EKLEME PARÇASI', 152),
  ('MALZEME', 'EL FENERİ', 153),
  ('MALZEME', 'ELEKTROT ÇAKMA TAKOZU', 154),
  ('MALZEME', 'ELEKTROT RUTİL - 3x2.5', 155),
  ('MALZEME', 'ELEKTROT SİVRİ UCU', 156),
  ('MALZEME', 'ENTEGRE SIVAMATİK - İÇ/25KG', 157),
  ('MALZEME', 'EPS BLOK - 40*35*100', 158),
  ('MALZEME', 'FIRÇA - BADANA', 159),
  ('MALZEME', 'FIRÇA - ROBOT', 160),
  ('MALZEME', 'FIRÇA TAKOZ - SU ATMA', 161),
  ('MALZEME', 'FLANŞ ADAPTÖRÜ - Ø63', 162),
  ('MALZEME', 'FLANŞ ADAPTÖRÜ - Ø75', 163),
  ('MALZEME', 'FLANŞ ADAPTÖRÜ - Ø90', 164),
  ('MALZEME', 'FLANŞLI DENGE KABI - DN 200', 165),
  ('MALZEME', 'GALVANİZ CİVATA - M16x70', 166),
  ('MALZEME', 'GALVANİZ KONİK REKOR (2-1/2)', 167),
  ('MALZEME', 'GALVANİZ KONİK REKOR (2)', 168),
  ('MALZEME', 'GALVANİZ PUL - M16', 169),
  ('MALZEME', 'GALVANİZ SOMUN - M16', 170),
  ('MALZEME', 'GAZ BETON (60*25*5)', 171),
  ('MALZEME', 'GÖMLEKLİ DÜBEL - M10', 172),
  ('MALZEME', 'GÖNYE TAŞÇI - 100X50 CM', 173),
  ('MALZEME', 'HAMMERFAST WP 205 ESNEK A VE B BİLEŞENİ 20+6 KG', 174),
  ('MALZEME', 'HAZIR BETON - C20/25', 175),
  ('MALZEME', 'HELA TAŞI - WC', 176),
  ('MALZEME', 'HİDROLİK HORTUM', 177),
  ('MALZEME', 'HİDROLİK YAĞI - 16 LT', 178),
  ('MALZEME', 'ISITMA SUYU SENSÖRÜ', 179),
  ('MALZEME', 'ISLAK ZEMİN YALITIM MALZEMESİ - KOVA', 180),
  ('MALZEME', 'ISLAK ZEMİN YALITIM MALZEMESİ - TORBA', 181),
  ('MALZEME', 'İSKARPELA - 30MM', 182),
  ('MALZEME', 'İŞ AYAKKABISI - A', 183),
  ('MALZEME', 'İŞ AYAKKABISI - B', 184),
  ('MALZEME', 'İŞÇİ PANTOLONU', 185),
  ('MALZEME', 'KABLO - 16 MM NYA', 186),
  ('MALZEME', 'KABLO - 2*1.5 LIHCH FE 180', 187),
  ('MALZEME', 'KABLO - 25MM NYA HF', 188),
  ('MALZEME', 'KABLO - 3*4 N2XH KABLO', 189),
  ('MALZEME', 'KABLO - 4*16 N2XH', 190),
  ('MALZEME', 'KABLO - 4*16 N2XH FE 180', 191),
  ('MALZEME', 'KABLO - 4*25 N2XH', 192),
  ('MALZEME', 'KABLO - 5*4 N2XH', 193),
  ('MALZEME', 'KABLO - 5*6 N2XH', 194),
  ('MALZEME', 'KABLO - 5*6 N2XH FE 180', 195),
  ('MALZEME', 'KABLO - CAT 6 HF', 196),
  ('MALZEME', 'KABLO - RG11/U-6 HF', 197),
  ('MALZEME', 'KABLO TTR MAKARALI 3X2.5 40 MT', 198),
  ('MALZEME', 'KANGAL BORU - Q32', 199),
  ('MALZEME', 'KAPI KOLU', 200),
  ('MALZEME', 'KAPLİN MANŞON - Q32', 201),
  ('MALZEME', 'KAPLİN TE - 32Q', 202),
  ('MALZEME', 'KAYNAK PAFTA LOKMASI - Q20', 203),
  ('MALZEME', 'KIRICI - BOSCH GBH 2- 26 DRE MATKAP', 204),
  ('MALZEME', 'KIRICI - MAKİTA HR 2470 MATKAP', 205),
  ('MALZEME', 'KIRICI - TOTAL TH3092288 MATKAP', 206),
  ('MALZEME', 'KLİPS', 207),
  ('MALZEME', 'KÖŞEBENT - FAYANS 10MM', 208),
  ('MALZEME', 'KUM - ŞAP 03', 209),
  ('MALZEME', 'LİN LİFE - ANAHTAR DÜĞME', 210),
  ('MALZEME', 'LİN LİFE - DÖRTLÜ ÇERÇEVE', 211),
  ('MALZEME', 'LİN LİFE - HDMI KONNEKTÖR + KAPAK', 212),
  ('MALZEME', 'LİN LİFE - İKİLİ ÇERÇEVE', 213),
  ('MALZEME', 'LİN LİFE - İKİLİ DATA JACKSIZ + KAPAK', 214),
  ('MALZEME', 'LİN LİFE - KOMÜTATÖR DÜĞME', 215),
  ('MALZEME', 'LİN LİFE - TEKLİ ÇERÇEVE', 216),
  ('MALZEME', 'LİN LİFE - TEKLİ NÜMERİS CAT 3 + KAPAK', 217),
  ('MALZEME', 'LİN LİFE - TOPRAKLI PRİZ + KAPAK', 218),
  ('MALZEME', 'LİN LİFE - TOPRAKLI PRİZ Ç.K + KAPAK', 219),
  ('MALZEME', 'LİN LİFE - UPS PRİZ Ç.K + KAPAK', 220),
  ('MALZEME', 'LİN LİFE - UYDU PRİZ F KONSONLU + KAPAK', 221),
  ('MALZEME', 'LİN LİFE - VAVİEN DÜĞME', 222),
  ('MALZEME', 'MALA - DERZ', 223),
  ('MALZEME', 'MALA - KAUÇUKLU 28 CM', 224),
  ('MALZEME', 'MALA - SÜNGERLİ', 225),
  ('MALZEME', 'MEMBRAN - BÜTÜM KATKILI - 3MM', 226),
  ('MALZEME', 'MUHAFAZA KUTUSU SETİ', 227),
  ('MALZEME', 'MUSLUK - BAHÇE 1/2''''', 228),
  ('MALZEME', 'NORM BUAT H/F', 229),
  ('MALZEME', 'NOVACOM NVC-LEDHQ43A CCTV MONİTÖR HDMI-VGA-AUDIO (4K -2160P 30Hz)', 230),
  ('MALZEME', 'NOVACOM VİVİ K5000 FULL HD PROJEKSİYON (3500ANSI) 1920*1080P', 231),
  ('MALZEME', 'PLASTİK BUAT - TERMO 110*110', 232),
  ('MALZEME', 'PLASTİK ÇİVİLİ DÜBEL', 233),
  ('MALZEME', 'PLASTİK KORGE BORU - Q50', 234),
  ('MALZEME', 'PLASTİK KUTULU TEST KLEMENSİ 2mm', 235),
  ('MALZEME', 'Q42 GALVANİZLİ MUHAFAZA BORUSU L=3000 (DİŞSİZ)', 236),
  ('MALZEME', 'RAL 7047 - 20 KG', 237),
  ('MALZEME', 'RAL 9016 - 20 KG', 238),
  ('MALZEME', 'RAVATHERM STONEWOLL - 60*600*1200MM', 239),
  ('MALZEME', 'SERAMİK - 30*60', 240),
  ('MALZEME', 'SERAMİK - ZEMİN 42*42', 241),
  ('MALZEME', 'SERAMİK - ZEMİN 60*120', 242),
  ('MALZEME', 'SERAMİK - ZEMİN 60*60', 243),
  ('MALZEME', 'SIRIK TELESKOPİK AYARLI 3 MT', 244),
  ('MALZEME', 'SIVA ALÇISI - İZOGİPS - 35 KG', 245),
  ('MALZEME', 'KABLO TEST CİHAZI - UNIT UT-682D', 246),
  ('MALZEME', 'KAFA LAMBASI', 247),
  ('MALZEME', 'KAMA DUVAR', 248),
  ('MALZEME', 'KAPALI GENLEŞME TANKI - 2500 LT', 249),
  ('MALZEME', 'KASKAD SENSÖRÜ', 250),
  ('MALZEME', 'KAYMAK KİREÇ - TORBALI', 251),
  ('MALZEME', 'KAZAN - DUVAR TİPİ YOĞUŞMALI FELİS', 252),
  ('MALZEME', 'KERESTE', 253),
  ('MALZEME', 'KIRICI - TOTAL TH309288', 254),
  ('MALZEME', 'KİREMİT - MAHYA 3 YOL SİYAH', 255),
  ('MALZEME', 'KİREMİT - MAHYA SİYAH', 256),
  ('MALZEME', 'KİREMİT - PERLİT SİYAH', 257),
  ('MALZEME', 'KLİNGRİK CONTA - 125', 258),
  ('MALZEME', 'KLİNGRİK CONTA - 200', 259),
  ('MALZEME', 'KLİNGRİK CONTA - 65', 260),
  ('MALZEME', 'KLİNGRİK CONTA - 80', 261),
  ('MALZEME', 'KOLLEKTÖR DOLABI - 1 NOLU', 262),
  ('MALZEME', 'KONTROL PANELİ - EKRANLI KASKAD', 263),
  ('MALZEME', 'KOZALAK PANÇ SETİ 3''LÜ', 264),
  ('MALZEME', 'KÖŞEBENT MAKASI', 265),
  ('MALZEME', 'M16 GİJON - 1MT', 266),
  ('MALZEME', 'MACUN KÜREĞİ', 267),
  ('MALZEME', 'MAKARA', 268),
  ('MALZEME', 'MANTOLAMA FİLELİ KÖŞE - 2.5M', 269),
  ('MALZEME', 'MANTOLAMA YAPIŞTIRICI - 25 KG', 270),
  ('MALZEME', 'MAPA - OMEGA TONAJLI 12 TON', 271),
  ('MALZEME', 'MASTAR ALÜMİNYUM BIÇAK - İNCE', 272),
  ('MALZEME', 'MASTAR ALÜMİNYUM BIÇAK - KALIN', 273),
  ('MALZEME', 'MEGA SW PLUS LEVHA - 80MM 600X1200', 274),
  ('MALZEME', 'MEMBRAN (-20)', 275),
  ('MALZEME', 'METRE ŞERİT - 50 MT', 276),
  ('MALZEME', 'METRE ŞERİT - 8 MT', 277),
  ('MALZEME', 'MOTOR YAĞI 15/40 - 16LT', 278),
  ('MALZEME', 'NPU DEMİR - 65', 279),
  ('MALZEME', 'PABUÇ - 25 MM SKP', 280),
  ('MALZEME', '25'''' 1/2 DIŞ DİŞ ADAPTÖR', 281),
  ('MALZEME', '3 Çıkışlı Kollektör (Kırmızı- Mavi 2''li Takım)', 282),
  ('MALZEME', '3'''' KELEPÇE SOMUNLU', 283),
  ('MALZEME', '3*2.5 NHXMH KABLO', 284),
  ('MALZEME', '3*32A W OTOMAT SİGORTA', 285),
  ('MALZEME', '3*63 A OTOMAT SİGORTA', 286),
  ('MALZEME', '3/4 " SOMUNLU KELEPCE -175-', 287),
  ('MALZEME', '3/4" GALVANİZLİ BORU', 288),
  ('MALZEME', '3/4" TRİFONLU KELEPÇE KISA', 289),
  ('MALZEME', '32'' 1'' DIŞ DİŞLİ RAKOR', 290),
  ('MALZEME', '3X25 HF TTR KABLO', 291),
  ('MALZEME', '4 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım)', 292),
  ('MALZEME', '4" GALVANİZLİ BORU', 293),
  ('MALZEME', '4" SOMUNLU KELEPСЕ-30-', 294),
  ('MALZEME', '4*21/2" GALVANİZ REDÜKSİYON TD', 295),
  ('MALZEME', '40*40 U PERFORE', 296),
  ('MALZEME', '5 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım )', 297),
  ('MALZEME', '5'''' KELEPÇE TRİFONLU', 298),
  ('MALZEME', '50 Kalde 32 Tapa', 299),
  ('MALZEME', '50 Kalde Atıksu Dirsek (45)', 300),
  ('MALZEME', '50 Kalde Atıksu Dirsek (87°)', 301),
  ('MALZEME', '50 MM MAKARON SİYAH', 302),
  ('MALZEME', '50*50 U PERFORE', 303),
  ('MALZEME', '50X1000 Kalde Tip1 PVC U Boru B Tipi', 304),
  ('MALZEME', '50X2000 Kalde Tip1 PVC U Boru B Tipi', 305),
  ('MALZEME', '50X50 Kalde Atıksu Tek Çatal (45°)', 306),
  ('MALZEME', '6 Çıkışlı Kollektör (Kırmızı - Mavi 2''li )', 307),
  ('MALZEME', '7 Çıkışlı Kollektör (Kımızı - Mavi 2''li Takım)', 308),
  ('MALZEME', 'PABUÇ - 70 MM SKP', 309),
  ('MALZEME', '75 Kalde Atıksu Dirsek (45°)', 310),
  ('MALZEME', '75 Kalde Atıksu Dirsek (87°)', 311),
  ('MALZEME', '75X1000 Kalde Tip1 PVC U Boru B Tipi', 312),
  ('MALZEME', '75X2000 Kalde Tip1 PVC U Boru B Tipi', 313),
  ('MALZEME', '75X3000 Kalde Tip1 PVC U Boru B Tipi', 314),
  ('MALZEME', '75X50 Kalde Atıksu Tek Çatal (45°)', 315),
  ('MALZEME', '75X500 Kalde Tip1 PVC U Boru B Tipi', 316),
  ('MALZEME', '75X75 Kalde Atıksu Tek Çatal (45°)', 317),
  ('MALZEME', '8 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım )', 318),
  ('MALZEME', '8 MM PLASTİK DÜBEL', 319),
  ('MALZEME', '9 Çıkışlı Kollektör (Kırmızı - Mavi 2''li Takım)', 320),
  ('MALZEME', '90°190 ŞANTİYE RANZASI (0.90MM)', 321)
ON CONFLICT ("grup", "deger") DO NOTHING;

INSERT INTO "Secenek" ("grup", "deger", "sira") VALUES
  ('MALZEME', '90°190 YAYLI YATAK', 322),
  ('MALZEME', 'PABUÇ - 95 MM SKP', 323),
  ('MALZEME', 'ADERANS ARTIRICI', 324),
  ('MALZEME', 'AGRAF 40 CM', 325),
  ('MALZEME', 'AHŞAP PALET', 326),
  ('MALZEME', 'AKÇALI 320 SPREY BOYA KIRMIZI 400 ML', 327),
  ('MALZEME', 'ALCI SIVA FİLESİ', 328),
  ('MALZEME', 'ALÇI - SATEN', 329),
  ('MALZEME', 'ALÇI - SIVA', 330),
  ('MALZEME', 'ALÇI KÖŞE PROFİLİ', 331),
  ('MALZEME', 'ALÇIPAN BEYAZ (1200x2500x12.5 MM)', 332),
  ('MALZEME', 'ALÇIPAN KASA', 333),
  ('MALZEME', 'ALÇIPAN KLİPSİ', 334),
  ('MALZEME', 'ALÇIPAN VİDASI', 335),
  ('MALZEME', 'ALET SAPI', 336),
  ('MALZEME', 'ALYAN TAKIMI - 8 PARÇA', 337),
  ('MALZEME', 'AMPUL 9 W BEYAZ', 338),
  ('MALZEME', 'ANAHTAR TAKIMI - 21 PARÇA', 339),
  ('MALZEME', 'ANAHTAR TAKIMI 12 PARÇA', 340),
  ('MALZEME', 'ANKRAJ LAMASI EKO (40*150*50MM)', 341),
  ('MALZEME', 'ARA KESME VALFİ - Q25', 342),
  ('MALZEME', 'ARMATÜR', 343),
  ('MALZEME', 'ASKAYNAK AS R-143 ELEKTROT RUTIL 2.5x350 (100AD)', 344),
  ('MALZEME', 'ASKILIK PORTMANTO', 345),
  ('MALZEME', 'ASMA KİLİT', 346),
  ('MALZEME', 'ASMA KİLİT DÖKÜM GRİ 50 MM', 347),
  ('MALZEME', 'ASMA KİLİT SARI 63MM', 348),
  ('MALZEME', 'ASTAR 7.5 LT', 349),
  ('MALZEME', 'ATIK KUTUSU 70 LT MAVİ', 350),
  ('MALZEME', 'Atıksu Boru - 110x250 Kalde 3.2', 351),
  ('MALZEME', 'Atıksu Boru - 50X250 Kalde 3.2', 352),
  ('MALZEME', 'Atıksu Boru - 50x500 Kalde 3.2', 353),
  ('MALZEME', 'Atıksu Boru - 75x250 Kalde 3.2', 354),
  ('MALZEME', 'AWOX ECOTEC ISITICI INFRARED DUVAR TİPİ 2500 W', 355),
  ('MALZEME', 'AYGIPS SATEN PERDAH ALÇISI 25 KG', 356),
  ('MALZEME', 'BAĞ TELİ', 357),
  ('MALZEME', 'BAKIR KABLO', 358),
  ('MALZEME', 'BALYOZ 3-4-5 KG', 359),
  ('MALZEME', 'BALYOZ 4 KG', 360),
  ('MALZEME', 'BALYOZ 5 KG', 361),
  ('MALZEME', 'BALYOZ DÜZ 3 KG', 362),
  ('MALZEME', 'BALYOZ DÜZ 4 KG', 363),
  ('MALZEME', 'BALYOZ DÜZ 8 KG', 364),
  ('MALZEME', 'BALYOZ SAPI', 365),
  ('MALZEME', 'BANT', 366),
  ('MALZEME', 'BANT PVC SİYАН 5 CМ X 25 MT (İZOLASYON)', 367),
  ('MALZEME', 'BANYO BATARYASI', 368),
  ('MALZEME', 'BANYO PERDESÍ', 369),
  ('MALZEME', 'BARDAK KARTON 7 OZ (3000/AD)', 370),
  ('MALZEME', 'BARET', 371),
  ('MALZEME', 'BARET - 3M', 372),
  ('MALZEME', 'BARET İSCİ DÜZ SARI', 373),
  ('MALZEME', 'BARET MÜHENDİS AYARLI BEYAZ', 374),
  ('MALZEME', 'BARET MÜHENDİS AYARLI SARI', 375),
  ('MALZEME', 'BARİYER YERLİ KOPMAZ 80 GR (1x50 MT)', 376),
  ('MALZEME', 'BATTANİYE İŞÇİ PELUŞ', 377),
  ('MALZEME', 'BAYMAX GOLDEN BX-12 NUBUK BAĞCIKLI AYAKKABI NO:41', 378),
  ('MALZEME', 'BAYMAX SİLVER S-01 SÜET CIRTLI AYAKKABI NO:40', 379),
  ('MALZEME', 'BERE', 380),
  ('MALZEME', 'BEYAZ SİLİKON', 381),
  ('MALZEME', 'BEYBİ KN2 FLEX NİTRİL ELDİVEN NO:10', 382),
  ('MALZEME', 'BEYBİ PN5 NÍTRİL ELDİVEN NO:9-10', 383),
  ('MALZEME', 'BEZ DOLAP', 384),
  ('MALZEME', 'BEZİR YAĞI 1/1', 385),
  ('MALZEME', 'BHD DERZ BANDI 100 MMx90 MT', 386),
  ('MALZEME', 'BİDON GAGALI 25 LT', 387),
  ('MALZEME', 'BİLEZİK 800*40', 388),
  ('MALZEME', 'BİLEZİK MAHRUTİ KUM', 389),
  ('MALZEME', 'BİTS UC PH2 YILDIZ 25 MM', 390),
  ('MALZEME', 'BİTS UC PH2 YILDIZ 50 MM', 391),
  ('MALZEME', 'BİTS UÇ PH2 YILDIZ 150MM', 392),
  ('MALZEME', 'BİTS UÇ SETİ', 393),
  ('MALZEME', 'BORU - ÇİM BETON 22x25MM', 394),
  ('MALZEME', 'BORU KILIFI İZOLE', 395),
  ('MALZEME', 'Boru Ø63/PN 20 Beyaz Kalde - PP Fiberli', 396),
  ('MALZEME', 'BOSCH BT 150 TRİPOD AYAK', 397),
  ('MALZEME', 'BOSCH METAL KESİci 115x2.5x22', 398),
  ('MALZEME', 'BOSCH METAL KESİCİ 180x3X22', 399),
  ('MALZEME', 'BOSCH METAL KESİCİ 230X3X22', 400),
  ('MALZEME', 'BOŞ', 401),
  ('MALZEME', 'BOYA - BEYAZ SPREY', 402),
  ('MALZEME', 'BOYA - GRİ SPREY', 403),
  ('MALZEME', 'BOYA - İÇ CEPHE KARDELEN', 404),
  ('MALZEME', 'BOYA - KIRMIZI SPREY', 405),
  ('MALZEME', 'BOYA KARIŞTIRICI', 406),
  ('MALZEME', 'BOYA- TAVAN BOYASI 3.5 LT', 407),
  ('MALZEME', 'BRANDA', 408),
  ('MALZEME', 'BRANDA ÇADIR 10X10', 409),
  ('MALZEME', 'BRANDA NAYLON SEFFAF', 410),
  ('MALZEME', 'C16/20 MİKSERLİ', 411),
  ('MALZEME', 'C16/20 POMPALI BETON', 412),
  ('MALZEME', 'C25/30 MİKSERLİ BETON', 413),
  ('MALZEME', 'C30/37 BRÜT BETON', 414),
  ('MALZEME', 'C30/37 POMPALI BETON', 415),
  ('MALZEME', 'ÇALI FIRÇASI', 416),
  ('MALZEME', 'CAPAK GÖZLÜĞÜ', 417),
  ('MALZEME', 'CARASKAL 3 TON 5MT ZİNCİRLİ', 418),
  ('MALZEME', 'CEKİC SAPI 1.5 KG', 419),
  ('MALZEME', 'CELİK BURUNLU AYAKKABI SVM', 420),
  ('MALZEME', 'CIMENTО 32.5 50 KG', 421),
  ('MALZEME', 'CİZME İSCİ SARI UZUN KONC NO:45', 422),
  ('MALZEME', 'CONTA', 423),
  ('MALZEME', 'CONTA LASTIK 1/2', 424),
  ('MALZEME', 'CTM FIRÇA ÇANAK SAÇAKLI 125MM', 425),
  ('MALZEME', 'ÇALIŞMA MASASI', 426),
  ('MALZEME', 'ÇAY MAKİNESİ - MİCROSTAR 1800W', 427),
  ('MALZEME', 'ÇEK PAS', 428),
  ('MALZEME', 'ÇEKİÇ', 429),
  ('MALZEME', 'ÇEKİÇ AHŞAP SAPLI 1000GR', 430),
  ('MALZEME', 'ÇEKİÇ METAL SAPLI DÜZ 2000 GR', 431),
  ('MALZEME', 'ÇEKMELİ ÇELİK DÜBEL M8', 432),
  ('MALZEME', 'ÇELİK HALAT TUTUCU', 433),
  ('MALZEME', 'ÇIM PASPAY PERDE 25 MM (6-14 MM) (1000AD/Ç)', 434),
  ('MALZEME', 'ÇIMENTO 32.5 50 KG', 435),
  ('MALZEME', 'ÇIRPI İPİ BÜYÜK (130 MT)', 436),
  ('MALZEME', 'ÇİFT KANATLI KAPI', 437),
  ('MALZEME', 'ÇİM PAS PAY NORM 50 (8-24 MM) (500 AD/ C)-(13150)', 438),
  ('MALZEME', 'ÇİM PASPAY', 439),
  ('MALZEME', 'ÇİMENTO 32.5 50 KG', 440),
  ('MALZEME', 'ÇİMENTO 50 KG', 441),
  ('MALZEME', 'ÇİMFİX DÜBEL PLASTİK 8 MM (500 AD/PKT)', 442),
  ('MALZEME', 'ÇİMFİX YERE TESPIT KROŞESİ ÇİFTLİ', 443),
  ('MALZEME', 'ÇİVİ - BETON 5X100', 444),
  ('MALZEME', 'ÇİVİ - GAZLI TABANCA (750 ADET)', 445),
  ('MALZEME', 'ÇİVİ TABANCASI - AKDENİZ AKD30/38', 446),
  ('MALZEME', 'ÇİZME', 447),
  ('MALZEME', 'ÇOP KOVASI PLASTİK GRİ-SİYAH KAPAKLI 50LT', 448),
  ('MALZEME', 'ÇÖP KOVASI', 449),
  ('MALZEME', 'ÇÖP POŞETİ', 450),
  ('MALZEME', 'ÇUVAL', 451),
  ('MALZEME', 'ÇUVAL 60x90', 452),
  ('MALZEME', 'D.G.ANAHTAR KASA', 453),
  ('MALZEME', 'DALGIÇ POMPA - CATPOWER KİRLİ SU', 454),
  ('MALZEME', 'DALGIÇ POMPA - EİNHELL', 455),
  ('MALZEME', 'DALGIÇ POMPA - FACWVSD-1100WB 1100W', 456),
  ('MALZEME', 'DALGIÇ POMPA - VENEDİK PRO QSB-JH-400122', 457),
  ('MALZEME', 'DAMACANA SU', 458),
  ('MALZEME', 'DEKOR 063 SIVA MALASI AHSAP SAP 24 CM', 459),
  ('MALZEME', 'DEKOR 1081 EKSPORT RULO 25 CМ', 460),
  ('MALZEME', 'DEKOR 1084 EKSPORT KALORİFER (PARMAK) RULO 10 CM', 461),
  ('MALZEME', 'DERZ BANDI', 462),
  ('MALZEME', 'DERZ BANT', 463),
  ('MALZEME', 'DERZ DOLGU', 464),
  ('MALZEME', 'DIŞ DİŞLİ ADAPTÖR Ø25x3/4', 465),
  ('MALZEME', 'DOLAP', 466),
  ('MALZEME', 'DRENAJ LEVHASI - 40 M2', 467),
  ('MALZEME', 'DURACELL AA KALIN KALEM PIL 1.5 V', 468),
  ('MALZEME', 'DUŞ KANALI KROM 40 CM', 469),
  ('MALZEME', 'DUŞ KANALI KROM 50 CM', 470),
  ('MALZEME', 'DUŞ SETİ', 471),
  ('MALZEME', 'DUVAR C PROFILİ 75 MM', 472),
  ('MALZEME', 'DUVAR KONSOLU AHT.', 473),
  ('MALZEME', 'DUVAR U PROFILİ 75 MM', 474),
  ('MALZEME', 'DUY PORSELEN E40', 475),
  ('MALZEME', 'DUYAR KÜRESEL VANA DİŞLİ TİP PN16 3/4"', 476),
  ('MALZEME', 'DÜBEL - ÇELİK', 477),
  ('MALZEME', 'DÜBEL - ÇELİK M8x55MM', 478),
  ('MALZEME', 'DÜBEL - KAPALI KANCALI M10x115', 479),
  ('MALZEME', 'DÜBEL - PLASTİK', 480),
  ('MALZEME', 'DÜBEL ÇAKMA M12', 481),
  ('MALZEME', 'DÜBEL KAPALI KANCALI M10x115', 482),
  ('MALZEME', 'DÜBEL KLİPSLİ 10x110', 483),
  ('MALZEME', 'DÜBEL S TİPİ ÇEKME M8', 484),
  ('MALZEME', 'DÜBEL TABANCASI', 485),
  ('MALZEME', 'Eco Oynar Başlı Erkek Rakor Ø25X3/4 Beyaz', 486),
  ('MALZEME', 'EK MUF - 1KV 4*50 ISI BÜZ', 487),
  ('MALZEME', 'EK MUF - 3*35/16 NYY ISI BÜZ', 488),
  ('MALZEME', 'EK MUFU REÇİNELİ 4X6', 489),
  ('MALZEME', 'EL ARABASI', 490),
  ('MALZEME', 'ELDİVEN NİT 400', 491),
  ('MALZEME', 'ELEKTRİK BANDI', 492),
  ('MALZEME', 'ELEKTRİKLİ SU ISITICI', 493),
  ('MALZEME', 'ELEKTROT BAŞLIĞI', 494),
  ('MALZEME', 'ELEKTROT RUTİL', 495),
  ('MALZEME', 'ELEKTROT TESPİT L TİPİ 2*50 MM', 496),
  ('MALZEME', 'EMNİYET İKAZ ŞERİDİ', 497),
  ('MALZEME', 'EMNİYET İKAZ ŞERİDİ KIRMIZI-BEYAZ 360-380 MT', 498),
  ('MALZEME', 'EMNİYET KEMERİ', 499),
  ('MALZEME', 'EMNİYET KEMERİ PARAŞÜT TİPİ BEL DESTEKLİ', 500),
  ('MALZEME', 'EMNİYET ŞERİDİ (KIRMIZI-BEYAZ)', 501),
  ('MALZEME', 'EMS FORCE 5543 250ML TR-EN ETİKETLİ', 502),
  ('MALZEME', 'EPOKSİ - FISCHER 553098', 503),
  ('MALZEME', 'EPOKSİ TABANCASI - DEMİR', 504),
  ('MALZEME', 'EPOKSİ TABANCASI - FİSCHER PRO AKÜLÜ', 505),
  ('MALZEME', 'EPOKSİ TABANCASI - PLASTİK', 506),
  ('MALZEME', 'ERA TOOL İNOX KESiCi 115x1x22.23', 507),
  ('MALZEME', 'ERİYEN BANT', 508),
  ('MALZEME', 'EVA YAĞMURLUK İNCE ASTARLI SARI', 509),
  ('MALZEME', 'EVYE', 510),
  ('MALZEME', 'FAYANS DIS KÖSE ALÜMİNYUM', 511),
  ('MALZEME', 'FENTES ANİ SU ISITICI FNT-03(SOFBEN', 512),
  ('MALZEME', 'FIRÇ', 513),
  ('MALZEME', 'FIRÇA', 514),
  ('MALZEME', 'FIRÇA - KESTİRME', 515),
  ('MALZEME', 'FIRÇA SAPI', 516),
  ('MALZEME', 'FIRÇA SAPI AHŞAP 1. KALİTE 1.2MT', 517),
  ('MALZEME', 'FIS AM KİM. KARTUŞ DÜBEL TABANCASI', 518),
  ('MALZEME', 'FISCO ÇELİK METRE ŞERİT 30 MT', 519),
  ('MALZEME', 'FİLE', 520),
  ('MALZEME', 'FİNLUX 65LT TERMOSİFON', 521),
  ('MALZEME', 'FİSCHER TABANCA (DEMİR)', 522),
  ('MALZEME', 'FLASH DİSK - 64 GB KIOXIA U366', 523),
  ('MALZEME', 'FLEX NİTRİL ELDİVEN', 524),
  ('MALZEME', 'FLEXBLE DD BAĞLANTI 20 CM 3/8"x3/8"', 525),
  ('MALZEME', 'FLEXBLE DD BAĞLANTI 70 CM 3/8"x3/8"', 526),
  ('MALZEME', 'FLEXBLE ED BAĞLANTI 50 CM 3/8"x3/8"', 527),
  ('MALZEME', 'GALVANİZ DİRSEK TD (2-1/2)', 528),
  ('MALZEME', 'GALVANİZ KÖRTAPA (2-1/2)', 529),
  ('MALZEME', 'GALVANİZ KÖRTAPA (2)', 530),
  ('MALZEME', 'GALVANİZ NİPEL (1-1/4)', 531),
  ('MALZEME', 'GALVANİZ NİPEL (3/4)', 532),
  ('MALZEME', 'GALVANİZ REDÜKSİYON (1-1/4x3/4)', 533),
  ('MALZEME', 'GALVANİZ REDÜKSİYON (1x3/4)', 534),
  ('MALZEME', 'GALVANİZ REDÜKSİYON (2-1/2x1)', 535),
  ('MALZEME', 'GALVANİZ TE (1-1/4)', 536),
  ('MALZEME', 'GALVANİZLİ ZİNCİR', 537),
  ('MALZEME', 'GAZ BETON (60*25*10)', 538),
  ('MALZEME', 'GAZ BETON (60*25*15)', 539),
  ('MALZEME', 'GAZ BETON (60*25*20)', 540),
  ('MALZEME', 'GAZ BETON (60*25*25)', 541),
  ('MALZEME', 'GAZ BETON (60*25*30)', 542),
  ('MALZEME', 'GAZ BETON TESTERESİ', 543),
  ('MALZEME', 'GAZ BETON YAPIŞTIRICI - 25 KG', 544),
  ('MALZEME', 'GLOBE ELEKTRİK BANDI SİYAН 0.13 ММx19 MMx10 MT', 545),
  ('MALZEME', 'GNG FIS TOPRAKLI ERKEK DÜZ 1X16 A', 546),
  ('MALZEME', 'GNG PRİZ GRUP 3LÜ KAUÇUK TOPRAKLI 1X16 A', 547),
  ('MALZEME', 'GOLYAT', 548),
  ('MALZEME', 'GÖMME REZERVUAR', 549),
  ('MALZEME', 'GRES POMPASI - İZELTAŞ 500 CC', 550),
  ('MALZEME', 'GRES YAĞI', 551),
  ('MALZEME', 'GRES YAĞI KAUÇUKLU (YEŞİL) 14 KG', 552),
  ('MALZEME', 'GRES YAĞI SPREY 500 ML', 553),
  ('MALZEME', 'HAK PASPAY PERDE 1/25 (2000 AD/5)', 554),
  ('MALZEME', 'HALAT - CE BELGELİ 12 MM', 555),
  ('MALZEME', 'HALAT - İSKOTA', 556),
  ('MALZEME', 'HALAT İSKOTA', 557),
  ('MALZEME', 'HALAT POLYESTER', 558),
  ('MALZEME', 'HAMMERFAST HAMMERFUGA FLEX SATEN GRI 20 KG', 559),
  ('MALZEME', 'HARÇ SÖKÜCÜ 5 LT', 560),
  ('MALZEME', 'HAVA FİLTRESİ - DIŞ', 561),
  ('MALZEME', 'HAVA FİLTRESİ - İÇ', 562),
  ('MALZEME', 'HAVA HORTUMU KIRMIZI 8 MM', 563),
  ('MALZEME', 'HAVA ÜFLEME', 564),
  ('MALZEME', 'HAZIR BETON', 565),
  ('MALZEME', 'HAZIR BETON - C16/20', 566),
  ('MALZEME', 'HAZIR BETON - C25/30', 567),
  ('MALZEME', 'HAZIR BETON - C30/37', 568),
  ('MALZEME', 'HAZIR BETON - C30/37 KENDİNDEN YERLEŞEN', 569),
  ('MALZEME', 'HAZIR BETON - C8/10', 570),
  ('MALZEME', 'HF+AY 110x110x70 SÜ VİDALI KAPAK BUAT - GRİ', 571),
  ('MALZEME', 'HIZLI YAPIŞTIRICI - BEST', 572),
  ('MALZEME', 'HİLTİ GAZLI TABANCA ÇİVİSİ GX120 GC22 27MM 750 Lİ', 573),
  ('MALZEME', 'HORTUM', 574),
  ('MALZEME', 'HORTUM - ÖRGÜLÜ ŞEFFAF 1/2''''', 575),
  ('MALZEME', 'HORTUM EKİ PLASTİK 2"', 576),
  ('MALZEME', 'HORTUM TERMO 1/2''''', 577),
  ('MALZEME', 'HORTUM YANGIN 2"', 578),
  ('MALZEME', 'HÜRSAN PLASTİK KOVA YUMUŞAK NO:5', 579),
  ('MALZEME', 'HYFİX - GRİ', 580),
  ('MALZEME', 'HYFİX - KIRMIZI', 581),
  ('MALZEME', 'ISIKLAR GAZBETON TESTERESİ PLASTİK SAPLI 50 CM', 582),
  ('MALZEME', 'ISITICI', 583),
  ('MALZEME', 'ISITICI AYAĞI', 584),
  ('MALZEME', 'ISITICI REZİSTANSI', 585),
  ('MALZEME', 'ISPATULA', 586),
  ('MALZEME', 'ISPATULA SAPI', 587),
  ('MALZEME', 'İLAÇLAMA POMPASI 16 LT', 588),
  ('MALZEME', 'İLK YARDIM CANTASI DOLU SET', 589),
  ('MALZEME', 'İNŞAAT ÇİVİSİ 10 CM', 590),
  ('MALZEME', 'İNŞAAT ÇİVİSİ 6CM', 591),
  ('MALZEME', 'İSKELE TESLİM FORMU', 592),
  ('MALZEME', 'İŞ AYAKKABISI', 593),
  ('MALZEME', 'İŞ AYAKKABISI -', 594),
  ('MALZEME', 'İŞ ELDİVENİ', 595),
  ('MALZEME', 'İTİMAT YONCA 119 ARA MUSLUĞU 3', 596),
  ('MALZEME', 'İZAR BİTS UC SETİ 31 PARÇA İZAR67769', 597),
  ('MALZEME', 'İZELTAS ANAHTAR KOMBİNE TАКІМ 21 РARÇA', 598),
  ('MALZEME', 'İZELTAŞ KONTROL KALEMİ 190 MM', 599),
  ('MALZEME', 'İZELTAŞ KURBAĞACIK 8"', 600),
  ('MALZEME', 'İZELTAŞ TORX ALLEN ANAHTAR TAKIMI 8 PARCA', 601),
  ('MALZEME', 'JCB - HİDROLİK KIRICI UÇ', 602),
  ('MALZEME', 'KAAN S3 AYAKKABI Ç.B C.T NO:44', 603),
  ('MALZEME', 'KAAN S3 AYAKKABI С.В C.T NO:42', 604),
  ('MALZEME', 'KABLO - 2*1.5 LIHCH', 605),
  ('MALZEME', 'KABLO - 2*15 N2XH FE 180', 606),
  ('MALZEME', 'KABLO - 2*2*080+080 MM JHSTH', 607),
  ('MALZEME', 'KABLO - 3*1.5 N2XH FE 180', 608),
  ('MALZEME', 'KABLO - 3*1.5 TTR', 609),
  ('MALZEME', 'KABLO - 3*2.5 NHXMH', 610),
  ('MALZEME', 'KABLO - 5*25 N2XH', 611),
  ('MALZEME', 'KABLO - 5*6 NHXMH', 612),
  ('MALZEME', 'KABLO - 50 MM NYA GRİ', 613),
  ('MALZEME', 'KABLO - CAT 6 4*2*23 AWG LSZH', 614),
  ('MALZEME', 'KABLO - JHSTH 2x2x0.80', 615),
  ('MALZEME', 'KABLO - RG6/U-6 HF', 616),
  ('MALZEME', 'KABLO BAĞI BEYAZ 4.8x380 (100 AD/PAKET)', 617),
  ('MALZEME', 'KABLO BAĞI BEYAZ 4.8x380 (100AD/PAKET)', 618),
  ('MALZEME', 'KABLO KANALI AHT. 200X40X1.50MM L:2500MM (SDG)', 619),
  ('MALZEME', 'KABLO KANALI AHT.150X40X1.50MM L:2500MM (SDG)', 620),
  ('MALZEME', 'KABLO KANALI ASKI TASIYICI L TİPİ 40x40x3.00mm (SD', 621),
  ('MALZEME', 'KABLO KANALI DÖNÜŞ ELEMANI 90° 150x40x1.50mm (SDG)', 622),
  ('MALZEME', 'KABLO KANALI DÖNÜŞ ELEMANI 90° 200x40x1.50mm (SDG)', 623),
  ('MALZEME', 'KABLO KANALI DÖNÜŞ ELEMANI DÖRTLÜ 150x40x1.50mm (S', 624),
  ('MALZEME', 'KABLO KANALI DÖNÜŞ ELEMANI DÖRTLÜ 200x40x1.50mm (S', 625),
  ('MALZEME', 'KABLO KANALI DÖNÜŞ ELEMANI T 150x40x1.50mm (SDG)', 626),
  ('MALZEME', 'KABLO KANALI DÖNÜŞ ELEMANI T 200x40x1.50mm (SDG)', 627),
  ('MALZEME', 'KABLO KANALI EK ELEMANI AHT. 40x1.50mm (SDG)', 628),
  ('MALZEME', 'KABLO KANALI YAPISKANLI', 629),
  ('MALZEME', 'KABLO MERDİVENİ 200X40X2.00MM L:2500MM (SDG)', 630),
  ('MALZEME', 'KABLO TTR 1. KALİTE BAKIR 3X2.5', 631),
  ('MALZEME', 'KABLO TTR 3X2.5', 632),
  ('MALZEME', 'KABLO TTR MAKARALI 3x2.5 30 MT', 633),
  ('MALZEME', 'KABLOSUZ MOUSE - GRİ FRISBY FM-272WM', 634),
  ('MALZEME', 'KABLOSUZ MOUSE - LOGITECH M185 GRİ', 635),
  ('MALZEME', 'KALE ASMA KİLİT GRİ DÖKÜM 50 MM', 636),
  ('MALZEME', 'KALE ASMA KİLİT GRİ DÖKÜM 60 MM', 637),
  ('MALZEME', 'KALIP AYIRICI - S1000 BİDON 30 LT', 638),
  ('MALZEME', 'KALKER MALZEME', 639),
  ('MALZEME', 'KAPI KİLİT GÖVDESİ', 640),
  ('MALZEME', 'KAPI PENCERE FİTİLİ BEYAZ 2Lİ', 641),
  ('MALZEME', 'KAPLİN TE İÇ DİŞLİ 40MMx1 1/4''''', 642),
  ('MALZEME', 'KARBOSAN THINLINE İNOX KESİCİ 115x1x22.23', 643),
  ('MALZEME', 'KARDELEN AURA BOYA PLASTİK BEYAZ 10 KG', 644),
  ('MALZEME', 'KARDELEN AURA PLASTİK İC CEPHE', 645),
  ('MALZEME', 'KARTONPİER', 646),
  ('MALZEME', 'KAUÇUKLU 3 GRUP PRİZ', 647),
  ('MALZEME', 'KAYNAK BAŞ MASKESİ GE1321 GENİŞ CAMLI', 648),
  ('MALZEME', 'KAYNAK MAKİNESİ - ASKAYNAK INVERTER 205', 649),
  ('MALZEME', 'KAYNAK MASKESİ', 650),
  ('MALZEME', 'KAYNAKÇI ELDİVENİ', 651),
  ('MALZEME', 'KAZIMA RASPASI', 652),
  ('MALZEME', 'KAZMA', 653),
  ('MALZEME', 'KAZMA SAPI', 654),
  ('MALZEME', 'KELEPÇE', 655),
  ('MALZEME', 'KERPETEN', 656),
  ('MALZEME', 'KESER', 657),
  ('MALZEME', 'KESKI SDS MAX 18x400x40 MM', 658),
  ('MALZEME', 'KESKI SDS PLUS 14x250x40 мM', 659),
  ('MALZEME', 'KESKİ', 660),
  ('MALZEME', 'KESKİ SDS MAX 18X400X25MM', 661),
  ('MALZEME', 'KETEN', 662),
  ('MALZEME', 'KIRICI', 663),
  ('MALZEME', 'KIRICI - BOSCH GBH 12-52 D', 664),
  ('MALZEME', 'KIRICI - DAFLONG ELS65', 665),
  ('MALZEME', 'KIRICI - MAKİTA HM 1203 C', 666),
  ('MALZEME', 'KIRICI - MAKİTA HM 1802', 667),
  ('MALZEME', 'KIRICI - TOTAL TH215456', 668),
  ('MALZEME', 'KIRICI / DELİCİ MATKAP - TOTAL TH308268', 669),
  ('MALZEME', 'KIRMIZI PEX BORU - 16X2', 670),
  ('MALZEME', 'KİLİT', 671),
  ('MALZEME', 'KİMYASAL DÜBEL TABANCASI METAL 345ML', 672),
  ('MALZEME', 'KİMYASAL DÜBEL TABANCASI METAL 410ML', 673),
  ('MALZEME', 'KİTAPLIK', 674),
  ('MALZEME', 'KLEPSAN SU SAYAÇ REKORU', 675),
  ('MALZEME', 'KLEPSAN SÜZME SU SAYACI', 676),
  ('MALZEME', 'KLOZET', 677),
  ('MALZEME', 'KNAUF İZOGİPS SIVA ALÇISI 35 KG', 678),
  ('MALZEME', 'KNAUF SATENGİPS SATEN ALCISI 25 KG', 679),
  ('MALZEME', 'KOLİ BANDI', 680),
  ('MALZEME', 'KOLLEKTÖR - 2 ÇIKIŞLI MAVİ', 681),
  ('MALZEME', 'KOLLEKTÖR DOLABI 60*60*11', 682),
  ('MALZEME', 'KOLLEKTÖR DOLABI 80*60*11', 683),
  ('MALZEME', 'Kollektör Kelepçe Seti', 684),
  ('MALZEME', 'KOMPAK ŞALTER 3X400A 50kA', 685),
  ('MALZEME', 'KOMPAKTÖR - TO9.005.TP7100-2E', 686),
  ('MALZEME', 'KONTEYNER - (3*7)', 687),
  ('MALZEME', 'KONTEYNER - DUŞ / TUVALET', 688),
  ('MALZEME', 'KONTEYNER - DUŞ / TUVALET 3*7', 689),
  ('MALZEME', 'KONTROL KALEMİ', 690),
  ('MALZEME', 'KORUYUCU GÖZLÜK', 691),
  ('MALZEME', 'KOSTİK 500 GR', 692),
  ('MALZEME', 'KÖPÜK VE MUSLUK', 693),
  ('MALZEME', 'KÖŞE PROFİLİ', 694),
  ('MALZEME', 'KULAK TIKACI', 695),
  ('MALZEME', 'KULAK TIKACI KORDONLU', 696),
  ('MALZEME', 'KUM - 03', 697),
  ('MALZEME', 'KUM - 05 ALT TEMEL', 698),
  ('MALZEME', 'KUM - 0X38', 699),
  ('MALZEME', 'KUM - MİL', 700),
  ('MALZEME', 'KUMPAS DUITAL 150 MM', 701),
  ('MALZEME', 'KUMPAS VE METAL KESİCİ', 702),
  ('MALZEME', 'KURBAĞACIK - İZELTAŞ', 703),
  ('MALZEME', 'KURTAĞIZI KLEMENS', 704),
  ('MALZEME', 'KUTU PROFİL 40x60x2 MM', 705),
  ('MALZEME', 'KÜREK', 706),
  ('MALZEME', 'KÜREK DEMIR KESKİN', 707),
  ('MALZEME', 'KÜREK SAPI', 708),
  ('MALZEME', 'LANYARD HALATLI', 709),
  ('MALZEME', 'LAPTOP - Casper Excalibur 13620H', 710),
  ('MALZEME', 'LAPTOP - DELL VOSTRO N160PVNB3530U', 711),
  ('MALZEME', 'LAPTOP - Ideapad Slim 3 SPF58TTMA', 712),
  ('MALZEME', 'LASTİK FİTİL ATMA SETİ', 713),
  ('MALZEME', 'LASTİK FİTİLİ UZUN 25''Lİ', 714),
  ('MALZEME', 'LAVABO - AVİTA 45x55', 715),
  ('MALZEME', 'LAVABO AYAK', 716),
  ('MALZEME', 'LAVABO MALZEMELERİ', 717),
  ('MALZEME', 'LEVHA DIS CEPHE 1.2x2.4 MT 12.5 MM', 718),
  ('MALZEME', 'LİNE YER SÜZGECİ 15*15*50 (Y.C)', 719),
  ('MALZEME', 'Logitech M185 Kablosuz Mouse Gri 910-002235', 720),
  ('MALZEME', 'LOKMA - 10', 721)
ON CONFLICT ("grup", "deger") DO NOTHING;

INSERT INTO "Secenek" ("grup", "deger", "sira") VALUES
  ('MALZEME', 'LOKMA - 12MM', 722),
  ('MALZEME', 'LOKMA - 16MM', 723),
  ('MALZEME', 'LOKMA - 8MM', 724),
  ('MALZEME', 'LOKMA ADAPTÖRÜ', 725),
  ('MALZEME', 'LOKMA TAKIMI - İZELTAŞ 3/4'''' 14 PARÇA', 726),
  ('MALZEME', 'M.KOLTUĞU', 727),
  ('MALZEME', 'M.SIVA', 728),
  ('MALZEME', 'M10 25 GALVANİZLİ DEMİR CİVATA', 729),
  ('MALZEME', 'M10mm Flanşlı Somun (EG)', 730),
  ('MALZEME', 'M10x3000mm Askı Tiji (EG)', 731),
  ('MALZEME', 'M8 25 GALVANİZLİ DEMİR CİVATA', 732),
  ('MALZEME', 'M8 CELİK СЕКМЕ К.TAPALI DÜBEL', 733),
  ('MALZEME', 'M8 ÇELİK SOMUN', 734),
  ('MALZEME', 'M8 FLANŞLI SOMUN', 735),
  ('MALZEME', 'M8 GALVANİZ ROT (TİJ) 1 MT', 736),
  ('MALZEME', 'M8 PLASTİK DÜBEL', 737),
  ('MALZEME', 'M8mm Flanşlı Somun (EG)', 738),
  ('MALZEME', 'M8x15mm Bombe Başlı Cıvata (EG)', 739),
  ('MALZEME', 'M8x3000mm Askı Tiji (EG)', 740),
  ('MALZEME', 'MAHRUTİ 800 LÜK', 741),
  ('MALZEME', 'MAKET BIÇAĞI', 742),
  ('MALZEME', 'MAKET BIÇAĞI YEDEĞİ', 743),
  ('MALZEME', 'MAKET BIÇAĞI AĞZI 18 MM (10 LU)', 744),
  ('MALZEME', 'MAKET BIÇAĞI METAL 18 MM GRİ', 745),
  ('MALZEME', 'MAKİTA 28.6*510MM YASSI KESKİ', 746),
  ('MALZEME', 'MAKİTA 28.6*520MM SİVRİ KESKİ', 747),
  ('MALZEME', 'MALA - AÇIK PLASTİK SAPLI 40 CM', 748),
  ('MALZEME', 'MALA - TIRFIL', 749),
  ('MALZEME', 'MANİVELA', 750),
  ('MALZEME', 'MANOMETRO 16 BAR', 751),
  ('MALZEME', 'MANTOLAMA SIVASI 25 KG', 752),
  ('MALZEME', 'MANYETİK SOMUN ADAPTÖRÜ', 753),
  ('MALZEME', 'MAPA - DÜZ KİLİT 10 MM', 754),
  ('MALZEME', 'MASKE CAMI', 755),
  ('MALZEME', 'MASKELEME BANDI', 756),
  ('MALZEME', 'MASTAR ALÜMİNYUM KUTU 30x70x1 MM İNCE', 757),
  ('MALZEME', 'BÜYÜK BOYA RULO', 758),
  ('MALZEME', 'MASTER DÖVME ÇELİK SAPLI KESER', 759),
  ('MALZEME', 'MASTER FIRÇA KESTÍRME NO:3', 760),
  ('MALZEME', 'MASTER KAZIMA RASPASI 20CM', 761),
  ('MALZEME', 'MASTER MERMER ZIMPARASI CIRT 115 MM 150 KUM', 762),
  ('MALZEME', 'MATKAP - TOTAL TIDLI20668E DARBELİ-AKÜLÜ 66NM 20V', 763),
  ('MALZEME', 'MATKAP UCU - BÜYÜK', 764),
  ('MALZEME', 'MATKAP UCU', 765),
  ('MALZEME', 'MATKAP UCU 10MM', 766),
  ('MALZEME', 'MATKAP UCU 6 MM', 767),
  ('MALZEME', 'MATKAP UCU HSS 9 MM', 768),
  ('MALZEME', 'MATKAP UCU SDS 24X450', 769),
  ('MALZEME', 'MATKAP UCU SDS MAX 22x540', 770),
  ('MALZEME', 'MATKAP UCU SDS MAX 26x570', 771),
  ('MALZEME', 'MATKAP UCU SDS PLUS 20X450', 772),
  ('MALZEME', 'MATKAP UCU SDS PLUS 6X160', 773),
  ('MALZEME', 'MATKAP UCU SDS PLUS 7x160', 774),
  ('MALZEME', 'MATKAP UCU SDS PLUS 8X160', 775),
  ('MALZEME', 'MEMBRAN 2MM', 776),
  ('MALZEME', 'GALVANİZ NİPEL (1/2)', 777),
  ('MALZEME', 'OTOMAT SİGORTA', 778),
  ('MALZEME', 'PABUÇ - 120 MM SKP', 779),
  ('MALZEME', 'PATENT - 100', 780),
  ('MALZEME', 'PATENT KEP - 150', 781),
  ('MALZEME', 'PATENT KEP - 300', 782),
  ('MALZEME', 'PENSE - HİDROLİK PABUÇ SIKMA', 783),
  ('MALZEME', 'PLASTİK ECZA DOLABI', 784),
  ('MALZEME', 'PP İç Dişli Dirsek Ø25x1/2', 785),
  ('MALZEME', 'Q20 - HF+AY - SPİRAL BORU - GRİ - ORTA SERİ', 786),
  ('MALZEME', 'R2 1/2 TİGER HORTUM', 787),
  ('MALZEME', 'RANZA CİVATASI', 788),
  ('MALZEME', 'RANZA PULU', 789),
  ('MALZEME', 'RANZA SOMUNU', 790),
  ('MALZEME', 'RULO SAPI', 791),
  ('MALZEME', 'SAÇ PLAKA - 15x15', 792),
  ('MALZEME', 'SATENGİPS - 25 KG', 793),
  ('MALZEME', 'SIVA FİLESİ - 160 GR', 794),
  ('MALZEME', 'SIVAMATİK - 25 KG', 795),
  ('MALZEME', 'SİYAH REDÜKSİYON (2x3/4)', 796),
  ('MALZEME', 'SOM BAKIR ELEKTROT Q20 L =2000mm', 797),
  ('MALZEME', 'STREÇ FİLM - 200 MT', 798),
  ('MALZEME', 'STROPİYER', 799),
  ('MALZEME', 'SUSTA - PLASTİK 10 MT', 800),
  ('MALZEME', 'SUSTA - PLASTİK 20 MT', 801),
  ('MALZEME', 'SUSTA - PLASTİK 25 MT', 802),
  ('MALZEME', 'ŞARJLI UÇ SETİ 31 PARÇA', 803),
  ('MALZEME', 'MAVİ ANAHTAR KASA', 804),
  ('MALZEME', 'MAVİ ANAHTAR KASA KAPAK', 805),
  ('MALZEME', 'MAVİ PEX BORU - 16X2', 806),
  ('MALZEME', 'MAТKAР UCU SDS PLUS 7x160', 807),
  ('MALZEME', 'MENFEZ KAPAĞI - 50X50', 808),
  ('MALZEME', 'MENTESE MİL BİLYALI 24 MM', 809),
  ('MALZEME', 'MENTESE YÖNSÜZ CELİK 12 CM', 810),
  ('MALZEME', 'MENTEŞE', 811),
  ('MALZEME', 'MENTEŞE MİL 26 MM', 812),
  ('MALZEME', 'MERDİVEN AHŞAP 6 BASAMAK', 813),
  ('MALZEME', 'METAL SPİRAL KESİCİ', 814),
  ('MALZEME', 'METRE', 815),
  ('MALZEME', 'METRE SERIT 5 MT 19 MM', 816),
  ('MALZEME', 'METRE ŞERİT - 30M', 817),
  ('MALZEME', 'METRE ŞERİT - 5M', 818),
  ('MALZEME', 'MİNERAL YÜN', 819),
  ('MALZEME', 'MİNERALLİ SIVA 25 KG', 820),
  ('MALZEME', 'MİNİSAN DP1200Q YER ISITICI', 821),
  ('MALZEME', 'MİNİSAN SR3000 ISITICI INFRARED DUVAR TİPİ 3000 WATT', 822),
  ('MALZEME', 'MİNİSAN-MAXÍMUS DP1200Q YER ISITICI', 823),
  ('MALZEME', 'MİZAN ÇAY MAKİNESİ 60 BARDAK', 824),
  ('MALZEME', 'MİZAN ÇAY MAKİNESİ 80 BARDAK', 825),
  ('MALZEME', 'MONT', 826),
  ('MALZEME', 'MOP PASPAS APARATI METAL YAYLI+SAPLI DAR (ISLAK)', 827),
  ('MALZEME', 'MOP PASPAS İPİ DAR (ISLAK)', 828),
  ('MALZEME', 'MOTORİN', 829),
  ('MALZEME', 'MURC SDS MAX 18x400 MM', 830),
  ('MALZEME', 'MURC SDS PLUS 14x250 Mм', 831),
  ('MALZEME', 'MUSLUK', 832),
  ('MALZEME', 'MUSLUK ARA FİLTRELİ 1/2', 833),
  ('MALZEME', 'NAKLİYE BEDELİ', 834),
  ('MALZEME', 'NAYLON', 835),
  ('MALZEME', 'NERVÜRLÜ İNŞAAT DEMİRİ Q12', 836),
  ('MALZEME', 'NERVÜRLÜ İNŞAAT DEMİRİ Q14', 837),
  ('MALZEME', 'NERVÜRLÜ İNŞAAT DEMİRİ Q16', 838),
  ('MALZEME', 'NERVÜRLÜ İNŞAAT DEMİRİ Q18', 839),
  ('MALZEME', 'NERVÜRLÜ İNŞAAT DEMİRİ Q20', 840),
  ('MALZEME', 'NERVÜRLÜ İNŞAAT DEMİRİ Q8', 841),
  ('MALZEME', 'NEVRESÍM LASTÍKLİ FERMUARLI TEK RENK', 842),
  ('MALZEME', 'NEVRESİM', 843),
  ('MALZEME', 'NEVRESİM İŞÇİ 1.KALİTE', 844),
  ('MALZEME', 'NEVRESİM LASTİKLİ FERMUARLI TEK RENK', 845),
  ('MALZEME', 'NIPEL SARI 3/8"', 846),
  ('MALZEME', 'NORTHFİX 201 SİLİKON ŞEFFAF 280 GR', 847),
  ('MALZEME', 'NURGAZ NG 2600 PÜRMÜZ SETİ', 848),
  ('MALZEME', 'OK-151 PAS SÖKÜCÜ 1 KG', 849),
  ('MALZEME', 'OTOMATİK HAVA TAHLİYE MİNİJÖR CCCASE 1/2"', 850),
  ('MALZEME', 'OTOМАТ SİGORTA ANAH.C32 1x32 AMP - SIEMENS 6KA', 851),
  ('MALZEME', 'PABUÇ - 35 MM SKP', 852),
  ('MALZEME', 'PABUÇ - 50 MM SKP', 853),
  ('MALZEME', 'PAFTA KESME YAĞI', 854),
  ('MALZEME', 'PALALI CİZME C.B-C.T MIFLONLU NO:40', 855),
  ('MALZEME', 'PALALI CİZME C.B-C.T MİFLONLU NO:41', 856),
  ('MALZEME', 'PALALI CİZME C.B-C.T MİFLONLU NO:42', 857),
  ('MALZEME', 'PALALI CİZME C.B-C.T MİFLONLU NO:43', 858),
  ('MALZEME', 'PALALI CİZME C.B-C.T MİFLONLU NO:45-46', 859),
  ('MALZEME', 'PALALI ÇİZME C.B-C.T MİFLONLU NO:41', 860),
  ('MALZEME', 'PALALI ÇİZME C.B.C.TABANLI NO:45-46', 861),
  ('MALZEME', 'PALALI ÇİZME C.B.C.TABANLI NO:47-48', 862),
  ('MALZEME', 'PANEL ÇİT DİREĞİ - H150', 863),
  ('MALZEME', 'PANEL ÇİT TAKIMI', 864),
  ('MALZEME', 'PANEL ÇİT TAKIMI - P150', 865),
  ('MALZEME', 'PARMAK RULO - BOYA', 866),
  ('MALZEME', 'PARS 110 S3 AYAKKABI C.B.C.T NO:45', 867),
  ('MALZEME', 'PARS 110 S3 AYAKKABI Ç.B.C.T NO:40', 868),
  ('MALZEME', 'PARS 110 S3 AYAKKABI С.В.CT NO:41', 869),
  ('MALZEME', 'PARS 110 S3 AYAKKABI С.В.CT NO:42', 870),
  ('MALZEME', 'PARS 110 S3 AYAKKABI С.В.CT NO:43', 871),
  ('MALZEME', 'PARS 110 S3 AYAKKABI С.В.CT NO:44', 872),
  ('MALZEME', 'PARS 110 S3 AYAKKABI С.В.С.T NO:46', 873),
  ('MALZEME', 'PARS 114 S1P SÜET AYAKKABI CB. CT. NO:42', 874),
  ('MALZEME', 'PARS 114 S1P SÜET AYAKKABI CB. CT. NO:43', 875),
  ('MALZEME', 'PARS 114 S1P SÜET AYAKKABI CB. CT. NO:44', 876),
  ('MALZEME', 'PARS 114 S1P SÜET AYAKKABI ÇB. ÇT. NO:38', 877),
  ('MALZEME', 'PARS 114 S1P SÜET AYAKKАВІ СВ. СT. NO:41', 878),
  ('MALZEME', 'PARS 114 S1P SÜET AYAKКАВІ CB. CT. NO:42', 879),
  ('MALZEME', 'PARS HSC 114 S1 AYAKKABI', 880),
  ('MALZEME', 'PAS SÖKÜCÜ', 881),
  ('MALZEME', 'PASPAS 120 CM', 882),
  ('MALZEME', 'PENSAMPERMETRE - UNİT UT 200A', 883),
  ('MALZEME', 'PENSE', 884),
  ('MALZEME', 'PENSE KOMBİNE 180 MM', 885),
  ('MALZEME', 'PERDE - STOR ZEBRA', 886),
  ('MALZEME', 'PILSA BATARYA BAĞ. PPRC KULAKLI DIRSEK 20 MMx1/2"', 887),
  ('MALZEME', 'PILSA BORU TIP 1 PVC 50/1000', 888),
  ('MALZEME', 'PÍLSA BORU TÍP 1 PVC 50/500', 889),
  ('MALZEME', 'PILSA BORU TİP 1 PVC 100/1000', 890),
  ('MALZEME', 'PILSA BORU TİP 1 PVC 100/2000', 891),
  ('MALZEME', 'PILSA BORU TİP 1 PVC 50/1000', 892),
  ('MALZEME', 'PILSA ÇATAL 45° PVC 50x50 MM', 893),
  ('MALZEME', 'PILSA DIRSEK 87 PVC 50 MM', 894),
  ('MALZEME', 'PILSA MANSON PPRC 20 MM', 895),
  ('MALZEME', 'PILSA TE PPRC 20 MM', 896),
  ('MALZEME', 'PILSA TE PPRC DIŞ DİŞ 20 MMx1/2''''', 897),
  ('MALZEME', 'PILSA TE PPRC İÇ DIŞ 20MMx1/2''''', 898),
  ('MALZEME', 'PILSA VANA PPRC KÜRESEL 20 MM', 899),
  ('MALZEME', 'PILSA YAPISTIRMA KÖRTAPA PPRC 20 MM', 900),
  ('MALZEME', 'PİK KAPAK HAFİF', 901),
  ('MALZEME', 'PİLSA ADAPTÖR PPRC İÇ DİS 20 MMx1/2"', 902),
  ('MALZEME', 'PİLSA BORU PPRC 20MM', 903),
  ('MALZEME', 'PİLSA DIRSEK 45° PPRC 20 MM', 904),
  ('MALZEME', 'PİLSA DİRSEK 45° PVC 50 MM', 905),
  ('MALZEME', 'PİLSA DİRSEK 87° PVC 100MM', 906),
  ('MALZEME', 'PİLSA DİRSEK 87° PVC 50 MM', 907),
  ('MALZEME', 'PİLSA DİRSEK 90 PPRC 20 MM', 908),
  ('MALZEME', 'PİLSA DİRSEK PPRC DIS DİS 20 MMx1/2"', 909),
  ('MALZEME', 'PİLSA DİRSEK PPRC IC DİS 20 MMx3/4"', 910),
  ('MALZEME', 'PİLSA DİRSEK PPRC OYNAR BAŞLI 20 MMx1/2', 911),
  ('MALZEME', 'PİLSA KAYAR MANŞON PVC 50 MM', 912),
  ('MALZEME', 'PİLSA KLİPS PPRC 20 MM', 913),
  ('MALZEME', 'PİLSA KŐRTAPA PPRC DİŞLİ 20 MMx 1/2"', 914),
  ('MALZEME', 'PİLSA KÖRTAPA PPRC DİŞLİ 20MMx1/2''''', 915),
  ('MALZEME', 'PİLSA KÖRTAPA PVC 100 MM', 916),
  ('MALZEME', 'PİLSA KÖRTAPA PVC 50 MM', 917),
  ('MALZEME', 'PİLSA MANSON PPRC 20 MM', 918),
  ('MALZEME', 'PİLSA TE PPRC 20 MM', 919),
  ('MALZEME', 'PİLSA VANA PPRC KÜRESEL 20MM', 920),
  ('MALZEME', 'PİLSA YAPISTIRMA KÖRTAPA PPRC 25 MM', 921),
  ('MALZEME', 'PİLSA YAPIŞTIRMA KÖRTAPA PPRC 20 MM', 922),
  ('MALZEME', 'PLASTİK KOVA', 923),
  ('MALZEME', 'PLASTİK SAPLI FARAŞ VE FIRÇA TAKIMI', 924),
  ('MALZEME', 'PLYWOOD', 925),
  ('MALZEME', 'POLİÜRETAN KÖPÜK 600 GR', 926),
  ('MALZEME', 'PP 45° Dirsek Ø20 Kalde Beyaz', 927),
  ('MALZEME', 'PP 45° Dirsek Ø25 Kalde Beyaz', 928),
  ('MALZEME', 'PP 45° Dirsek Ø32 Kalde Beyaz', 929),
  ('MALZEME', 'PP 45° Dirsek Ø40 Kalde Beyaz', 930),
  ('MALZEME', 'PP 45° Dirsek Ø50 Kalde Beyaz', 931),
  ('MALZEME', 'PP 45° Dirsek Ø63 Kalde Beyaz', 932),
  ('MALZEME', 'PP 45° Dirsek Ø75 Kalde Beyaz', 933),
  ('MALZEME', 'PP 45° Dirsek Ø90 Kalde Beyaz', 934),
  ('MALZEME', 'PP 90° Dirsek 090 Kalde Beyaz', 935),
  ('MALZEME', 'PP 90° Dirsek Ø20 Kalde Beyaz', 936),
  ('MALZEME', 'PP 90° Dirsek Ø25 Kalde Beyaz', 937),
  ('MALZEME', 'PP 90° Dirsek Ø32 Kalde Beyaz', 938),
  ('MALZEME', 'PP 90° Dirsek Ø40 Kalde Beyaz', 939),
  ('MALZEME', 'PP 90° Dirsek Ø50 Kalde Beyaz', 940),
  ('MALZEME', 'PP 90° Dirsek Ø63 Kalde Beyaz', 941),
  ('MALZEME', 'PP 90° Dirsek Ø75 Kalde Beyaz', 942),
  ('MALZEME', 'PP C Kavis Ø25 Kalde Beyaz', 943),
  ('MALZEME', 'PP Çiftli Batarya [Ym] Ø25×/2 Kalde Beyaz', 944),
  ('MALZEME', 'PP Dişi Dirsek Ø25×1/2 Kalde Beyaz', 945),
  ('MALZEME', 'PP Düz Boru Ø20/PN 20 Beyaz Kalde', 946),
  ('MALZEME', 'PP Düz Boru Ø25/PN 20 Beyaz Kalde', 947),
  ('MALZEME', 'PP Düz Boru Ø40/PN 20 Beyaz Kalde', 948),
  ('MALZEME', 'PP Erkek Nipel Ø25x3/4 Kalde Beyaz', 949),
  ('MALZEME', 'PP Fiberli Boru Ø20/PN 20 Beyaz Kalde', 950),
  ('MALZEME', 'PP Fiberli Boru Ø25/PN 20 Beyaz Kalde', 951),
  ('MALZEME', 'PP Fiberli Boru Ø32/PN 20 Beyaz Kalde', 952),
  ('MALZEME', 'PP Fiberli Boru Ø40/PN 20 Beyaz Kalde', 953),
  ('MALZEME', 'PP Fiberli Boru Ø50/PN 20 Beyaz Kalde', 954),
  ('MALZEME', 'PP Fiberli Boru Ø75/PN 20 Beyaz Kalde', 955),
  ('MALZEME', 'PP Fiberli Boru Ø90/PN 20 Beyaz Kalde', 956),
  ('MALZEME', 'PP Inegal Te 090/63/90 Kalde Beyaz', 957),
  ('MALZEME', 'PP Inegal Te Ø25/20/25 Kalde Beyaz', 958),
  ('MALZEME', 'PP Inegal Te Ø32/25/32 Kalde Beyaz', 959),
  ('MALZEME', 'PP İnegal Te Ø40/25/40 Kalde Beyaz', 960),
  ('MALZEME', 'PP İnegal Te Ø40/32/40 Kalde Beyaz', 961),
  ('MALZEME', 'PP İnegal Te Ø50/32/50 Kalde Beyaz', 962),
  ('MALZEME', 'PP İnegal Te Ø90/63/90 Kalde Beyaz', 963),
  ('MALZEME', 'PP Kapama Başlığı Ø20 Kalde Beyaz', 964),
  ('MALZEME', 'PP Kapama Başlığı Ø25 Kalde Beyaz', 965),
  ('MALZEME', 'PP Kapama Başlığı Ø32 Kalde Beyaz', 966),
  ('MALZEME', 'PP Kapama Başlığı Ø40 Kalde Beyaz', 967),
  ('MALZEME', 'PP Kapama Başlığı Ø50 Kalde Beyaz', 968),
  ('MALZEME', 'PP Kapama Başlığı Ø63 Kalde Beyaz', 969),
  ('MALZEME', 'PP Kapama Başlığı Ø75 Kalde Beyaz', 970),
  ('MALZEME', 'PP Kapama Başlığı Ø90 Kalde Beyaz', 971),
  ('MALZEME', 'PP Körtapa Ø20x1/2 Kalde Siyah', 972),
  ('MALZEME', 'PP Köse Düzeltme Seffaf Poşetli Siyah', 973),
  ('MALZEME', 'PP Manşon Ø20 Kalde Beyaz', 974),
  ('MALZEME', 'PP Manson Ø63 Kalde Beyaz', 975),
  ('MALZEME', 'PP Manşon Ø25 Kalde Beyaz', 976),
  ('MALZEME', 'PP Manşon Ø32 Kalde Beyaz', 977),
  ('MALZEME', 'PP Manşon Ø40 Kalde Beyaz', 978),
  ('MALZEME', 'PP Manşon Ø50 Kalde Beyaz', 979),
  ('MALZEME', 'PP Manşon Ø63 Kalde Beyaz', 980),
  ('MALZEME', 'PP Manşon Ø75 Kalde Beyaz', 981),
  ('MALZEME', 'PP Manşon Ø90 Kalde Beyaz', 982),
  ('MALZEME', 'PP Reduksıyon Ø32/20 Kalde Beyaz', 983),
  ('MALZEME', 'PP Redüksiyon - Ø25/20 Kalde Beyaz', 984),
  ('MALZEME', 'PP Reduksiyon Ø40/32 Kalde Beyaz', 985),
  ('MALZEME', 'PP Redüksiyon Ø32/25 Kalde Beyaz', 986),
  ('MALZEME', 'PP Redüksiyon Ø40/32 Kalde Beyaz', 987),
  ('MALZEME', 'PP Redüksiyon Ø50/40 Kalde Beyaz', 988),
  ('MALZEME', 'PP Redüksiyon Ø63/40 Kalde Beyaz', 989),
  ('MALZEME', 'PP Redüksiyon Ø63/50 Kalde Beyaz', 990),
  ('MALZEME', 'PP Redüksiyon Ø75/63 Kalde Beyaz', 991),
  ('MALZEME', 'PP Redüksiyon Ø90/75 Kalde Beyaz', 992),
  ('MALZEME', 'PP Spiral Kılçık 025 Kalde Mavi', 993),
  ('MALZEME', 'PP Te Ø20 Kalde Beyaz', 994),
  ('MALZEME', 'PP Te Ø25 Kalde Beyaz', 995),
  ('MALZEME', 'PP Te Ø32 Kalde Beyaz', 996),
  ('MALZEME', 'PP Te Ø40 Kalde Beyaz', 997),
  ('MALZEME', 'PP Te Ø50 Kalde Beyaz', 998),
  ('MALZEME', 'PP Te Ø63 Kalde Beyaz', 999),
  ('MALZEME', 'PP Te Ø75 Kalde Beyaz', 1000),
  ('MALZEME', 'PP Te Ø90 Kalde Beyaz', 1001),
  ('MALZEME', 'PP Tekli Kelepçe Ø25/27 Beyaz', 1002),
  ('MALZEME', 'PREMIUM LINE 6LI', 1003),
  ('MALZEME', 'PROFİL VE PASPAS', 1004),
  ('MALZEME', 'PROJEKTÖR - 200 W LED BEYAZ', 1005),
  ('MALZEME', 'PROJEKTÖR - 300 W LED BEYAZ', 1006),
  ('MALZEME', 'PROJEKTÖR ARMATÜRÜ LEDLİ 100 W IP66', 1007),
  ('MALZEME', 'PUL - M10', 1008),
  ('MALZEME', 'PUL - M8', 1009),
  ('MALZEME', 'PUL M8', 1010),
  ('MALZEME', 'PÜRMÜZ', 1011),
  ('MALZEME', 'PVC VE CAM', 1012),
  ('MALZEME', 'PVC ZEMİN', 1013),
  ('MALZEME', 'Q16 - HF SPİRAL BORU GRİ ORTA SERİ', 1014),
  ('MALZEME', 'Q18 -HF+AY - KANGAL BORU - TURUNCU - ORTA SERİ', 1015),
  ('MALZEME', 'Q18-HF-AY-KANGAL BORU-MAVİ-ORTA SERİ', 1016),
  ('MALZEME', 'Q20 TOPRAKLAMA ÇUBUĞU 2 MT', 1017),
  ('MALZEME', 'Q25-PE - KANGAL BORU - SİYAH - ORTA SERİ', 1018),
  ('MALZEME', 'Q8-Q8 KARE KLEMENS B.TİPİ', 1019),
  ('MALZEME', 'RAKORLU KÜRESEL VANA KALDE 1" KIRMIZI', 1020),
  ('MALZEME', 'RAKORLU KÜRESEL VANA KALDE 1" MAVİ', 1021),
  ('MALZEME', 'RANZA', 1022),
  ('MALZEME', 'RANZA AYAĞI', 1023),
  ('MALZEME', 'RANZA LÜX İŞÇİ 80x180 YATAY SAC DESTEKLİ', 1024),
  ('MALZEME', 'REZE', 1025),
  ('MALZEME', 'REZE (ORTA)', 1026),
  ('MALZEME', 'RIGIPS ALCIPAN VİDASI MATKAP UCLU 3.5x25', 1027),
  ('MALZEME', 'RİGİPS KARTONPİYER ALÇISI 30KG', 1028),
  ('MALZEME', 'ROKET DÜBEL 8 MM SARI(1*500)', 1029),
  ('MALZEME', 'RUBI FAYANS KESME ELMASI 10 MM 13/32', 1030),
  ('MALZEME', 'SAHA DAĞITIM PANOSU - BÜYÜK', 1031),
  ('MALZEME', 'SAHA PANOSU AYAKLI - KÜÇÜK', 1032),
  ('MALZEME', 'SANDALYE - PLASTİK', 1033),
  ('MALZEME', 'SAPAN POLYESTER 3 TON 6 MT 7:1', 1034),
  ('MALZEME', 'SAPAN POLYESTER 6 TON 6MT', 1035),
  ('MALZEME', 'SDS PLUS KESKİ-MURC', 1036),
  ('MALZEME', 'SEHPA', 1037),
  ('MALZEME', 'SELSİL SİLİKON SEFFAF 280 GR', 1038),
  ('MALZEME', 'SERAMİK 30*60', 1039),
  ('MALZEME', 'SERAMİK 30*60 BEYRUT BEYAZ', 1040),
  ('MALZEME', 'SERAMİK KLİPSİ 2MM (200AD)', 1041),
  ('MALZEME', 'SERAMİK TAKOZU', 1042),
  ('MALZEME', 'SERAMİK TAKOZU (100AD)', 1043),
  ('MALZEME', 'SERAMİK YAPIŞTIRICI - FRİGYA (25KG)', 1044),
  ('MALZEME', 'SERAMİK YAPIŞTIRICISI 25 KG', 1045),
  ('MALZEME', 'SEYYAR PRİZ UCU ( ERKEK - DİŞİ )', 1046),
  ('MALZEME', 'SIEMENS 3KA OTOMAT SİGORTA ANAH.B32 1x32 AMP.', 1047),
  ('MALZEME', 'SIEMENS 3KA OTOMAT SİGORTA ANAH.C32 3x32 AMP.', 1048),
  ('MALZEME', 'SIVA ALÇISI - 25 KG', 1049),
  ('MALZEME', 'SIVA ALTI ANAHTAR - PELSAN', 1050),
  ('MALZEME', 'SIVA ALTI OTOMAT KUTUSU 18''Lİ', 1051),
  ('MALZEME', 'SIVA MALASI', 1052),
  ('MALZEME', 'SIVA SÜNGERİ', 1053),
  ('MALZEME', 'SIVACI KÜREĞİ', 1054),
  ('MALZEME', 'SIVI EL SABUNU PEMBE 30 KG', 1055),
  ('MALZEME', 'SİBAX NS66 POLİÜRETAN MONTAJ KÖPÜK 600 GR', 1056),
  ('MALZEME', 'SİEMENS 10KA OTOMAT SİGORTA ANAH.C50', 1057),
  ('MALZEME', 'SİFON', 1058),
  ('MALZEME', 'SİFON LAVABO KÖRÜKLÜ', 1059),
  ('MALZEME', 'SİKA GROUT-212 25 KG', 1060),
  ('MALZEME', 'SİLİKON', 1061),
  ('MALZEME', 'SİYAH ÇANTA - PLM DREXEL 6300 15.6', 1062),
  ('MALZEME', 'SÖKÜ DÖVME 100 CM - MANİVELA', 1063),
  ('MALZEME', 'STAYER SUPER PLUS 200 B GE KAYNAK MAKİNESİ 200A', 1064),
  ('MALZEME', 'STRAFOR', 1065),
  ('MALZEME', 'SU TERAZİSİ', 1066),
  ('MALZEME', 'SU ZIMPARASI 80 KUM', 1067),
  ('MALZEME', 'SUNTA VİDASI 5*50', 1068),
  ('MALZEME', 'SÜPÜRGELİK - 6CM', 1069),
  ('MALZEME', 'SÜRGÜLÜ MERDİVEN', 1070),
  ('MALZEME', 'SÜZGEÇ YER ALT ÇIKIŞLI KROM', 1071),
  ('MALZEME', 'ŞAP 250', 1072),
  ('MALZEME', 'ŞEFFAF NAYLON VE AYAKKABI', 1073),
  ('MALZEME', 'ŞEFFAF SİLİKON', 1074),
  ('MALZEME', 'TAMİR HARCI - EMACO 25 KG', 1075),
  ('MALZEME', 'TAMİR HARCI - HAMMERFAST 25 KG', 1076),
  ('MALZEME', 'TAPA - 25MM', 1077),
  ('MALZEME', 'TAPA - 32 MM', 1078),
  ('MALZEME', 'Tapa - 50 Kalde 32', 1079),
  ('MALZEME', 'TAŞLAMA MAKİNASI - TOTAL TG10711556E 115 MM 750 W', 1080),
  ('MALZEME', 'TAŞLAMA MAKİNESİ - TOTAL TAGLI211545 AKÜLÜ 115 MM 5A', 1081),
  ('MALZEME', 'TAŞLAMA MAKİNESİ - TOTAL TG1252306E 230MM 2400 W', 1082),
  ('MALZEME', 'TAVA VİDASI VE SOMUNU - M8*15', 1083),
  ('MALZEME', 'TAVAN BOYA - 17.5 KG', 1084),
  ('MALZEME', 'TAVAN PROFİLİ', 1085),
  ('MALZEME', 'TAVAN PROFİLİ - C', 1086),
  ('MALZEME', 'TAVAN PROFİLİ - U', 1087),
  ('MALZEME', 'TAVAN PROJEKSİYON APARATI 30CM (PR 03)', 1088),
  ('MALZEME', 'TAVAN U PROFİLİ', 1089),
  ('MALZEME', 'TEFLON BANDI', 1090),
  ('MALZEME', 'TEK KİŞİLİK EKO PAMUKLU NEVRESİM TAKIMI', 1091),
  ('MALZEME', 'TEK KİŞİLİK ELYAF YORGAN', 1092),
  ('MALZEME', 'TEK SERPANTİLLİ BOYLER - 2000 LT', 1093),
  ('MALZEME', 'TEK SERPANTİLLİ BOYLER - 300 LT', 1094),
  ('MALZEME', 'TEKLİ İSKELE - 2MT', 1095),
  ('MALZEME', 'TEKNOBOND 401 S KİMYASAL DÜBEL 410 ML', 1096),
  ('MALZEME', 'TEKNOBOND 401S (410MIt', 1097),
  ('MALZEME', 'TEL FIRÇA - KÜÇÜK', 1098),
  ('MALZEME', 'TEL KİREMİT BAĞLAMA - GALVANİZLİ', 1099),
  ('MALZEME', 'TELESKOPİK DİREK - 6 MT', 1100),
  ('MALZEME', 'TELSİZ - ASELSAN PM665', 1101),
  ('MALZEME', 'TEMFLEX 1300 SİYAH BANT', 1102),
  ('MALZEME', 'TEMİZLİK ARABASI ÇİFT KOVALI (ISLAK)', 1103),
  ('MALZEME', 'TESTERE - BETON KANALI', 1104),
  ('MALZEME', 'TESTERE BETON KANALI 230 MM', 1105),
  ('MALZEME', 'TFA-0165 YANGIN ALARM BUTONLARI İÇİN PLASTİK KAPAK', 1106),
  ('MALZEME', 'TFD-1170 ANALOG ADRESLÍ DOĞALGAZ DEDEKTÖRÜ (HARİCİ BESLEMELİ)', 1107),
  ('MALZEME', 'TFD-2351 AKILLI ADRESLİ DAHİLİ İZOLATÖRLÜ OPTİK DUMAN DEDEKTÖRÜ (TABAN HARİÇ)', 1108),
  ('MALZEME', 'TFS-3192R KONVANSİYONEL FLAŞÖRLÜ YANGIN ALARM SİRENİ KIRMIZI (EN-54', 1109),
  ('MALZEME', 'TIRMIK', 1110),
  ('MALZEME', 'TIRMIK SAPI', 1111),
  ('MALZEME', 'TIRNAK', 1112),
  ('MALZEME', 'TIRNAK CİVATA SOMUNU', 1113),
  ('MALZEME', 'TIRNAK CİVATASI', 1114),
  ('MALZEME', 'TIRNAK ORTA', 1115),
  ('MALZEME', 'TIRNAK SOL', 1116),
  ('MALZEME', 'TİLKİ KUYRUĞU - MAX EXTRA', 1117),
  ('MALZEME', 'TİLKİ KUYRUĞU AĞZI', 1118),
  ('MALZEME', 'TİLKİ KUYRUĞU AĞZI - PROTER 201 AHŞAP PALET', 1119),
  ('MALZEME', 'TİNER - 1/1', 1120),
  ('MALZEME', 'TİNER TENEKE', 1121)
ON CONFLICT ("grup", "deger") DO NOTHING;

INSERT INTO "Secenek" ("grup", "deger", "sira") VALUES
  ('MALZEME', 'TOKMAK', 1122),
  ('MALZEME', 'TOPLANTI MASASI', 1123),
  ('MALZEME', 'TOPRAKLAMA ÇUBUĞU - Q16 1 MT', 1124),
  ('MALZEME', 'TOPRAKLAMA ÇUBUĞU KLEMENSİ', 1125),
  ('MALZEME', 'TOPRAKLAMA KAZIĞI - 2 MT', 1126),
  ('MALZEME', 'TOPRAKLAMA ŞERİDİ 30*3.5', 1127),
  ('MALZEME', 'TORNAVİDA', 1128),
  ('MALZEME', 'TORNAVİDA YILDIZ 6X125 MM', 1129),
  ('MALZEME', 'TOTAL BHP225 BASINÇLI YIKAMA MAKİNESİ 3200W', 1130),
  ('MALZEME', 'TOTAL THT561781 GAZLI CAM KESME', 1131),
  ('MALZEME', 'TOZ MASKESİ', 1132),
  ('MALZEME', 'TRANSPALET', 1133),
  ('MALZEME', 'TRAPEZ SAC', 1134),
  ('MALZEME', 'TULUM - BOYACI TEK KULLANIMLIK', 1135),
  ('MALZEME', 'UGR PH2*50 BİTS UÇ', 1136),
  ('MALZEME', 'UNV IPC2124LB-ASF28K-A2 4MP 28MM SESLİ BULLET KAMERA', 1137),
  ('MALZEME', 'UNV IPC322LB-ASF28K-A 2MP IP 2.8MM SESLİ DOME KAMERA', 1138),
  ('MALZEME', 'UZATMA 1/2"x3 CM', 1139),
  ('MALZEME', 'ÜSTÜBÜ - 1 KG', 1140),
  ('MALZEME', 'VANTİLATÖR', 1141),
  ('MALZEME', 'VARİL - 210 LT', 1142),
  ('MALZEME', 'VARTA SUPERLIFE ÇINK', 1143),
  ('MALZEME', 'VE-GE BANT CIFT TARAFLI ŞEFFAF 24 MM X25 MT', 1144),
  ('MALZEME', 'VE-GE BANT ÇİFT TARAFLI ŞEFFAF 18MM X25MT', 1145),
  ('MALZEME', 'VENTO S3 AYAKKABI NO:40', 1146),
  ('MALZEME', 'VENTO S3 AYAKKABI NO:41', 1147),
  ('MALZEME', 'VENTO S3 AYAKKABI NO:42', 1148),
  ('MALZEME', 'VENTO S3 AYAKKABI NO:43', 1149),
  ('MALZEME', 'VENTO S3 AYAKKABI NO:44', 1150),
  ('MALZEME', 'VIDA TRAPEZ 5.5x25 MM', 1151),
  ('MALZEME', 'VIDA TRAPEZ 5.5x76 MM', 1152),
  ('MALZEME', 'VİBRATÖR HORTUMU - 5 MT 45 MM', 1153),
  ('MALZEME', 'VİDA', 1154),
  ('MALZEME', 'VİDA - 3.5x25', 1155),
  ('MALZEME', 'VİDA - 39x16', 1156),
  ('MALZEME', 'VİDA - 5X40 SUNTA', 1157),
  ('MALZEME', 'VİDA - 5X70 SUNTA', 1158),
  ('MALZEME', 'VİDA - DÜBEL', 1159),
  ('MALZEME', 'VİDA 3.9x19 MM', 1160),
  ('MALZEME', 'VİDA 4.8x100 ММ', 1161),
  ('MALZEME', 'VİDA 4.8x32 MM', 1162),
  ('MALZEME', 'VİDA SUNTA 5x50 MM', 1163),
  ('MALZEME', 'VİDA SUNTA 5x60 MM', 1164),
  ('MALZEME', 'VİDA TRAPEZ 4.8x19 MM', 1165),
  ('MALZEME', 'VİKO KARRE 1 Lİ ÇERÇEVE', 1166),
  ('MALZEME', 'VİKO KARRE KAPAKLI TOPRAKLI PRİZ', 1167),
  ('MALZEME', 'VİKO NOVELLA ANAHTAR', 1168),
  ('MALZEME', 'VOLTAJ DEDEKTÖRÜ - UNIT UT-12D', 1169),
  ('MALZEME', 'XPS', 1170),
  ('MALZEME', 'XPS - 2 CM', 1171),
  ('MALZEME', 'XPS - 3 CM', 1172),
  ('MALZEME', 'XPS - 5 CM', 1173),
  ('MALZEME', 'YAĞ SÖKÜCÜ', 1174),
  ('MALZEME', 'YAĞLI RADYATÖR - ALTUS', 1175),
  ('MALZEME', 'YAĞMURLUK', 1176),
  ('MALZEME', 'YAN KESKİ - KNİPEX', 1177),
  ('MALZEME', 'YANGIN DOLABI VANALI HORTUMLU', 1178),
  ('MALZEME', 'YANGIN HİDRANTI - ÖKÇELİ', 1179),
  ('MALZEME', 'YANGIN HORTUMU - 30MT', 1180),
  ('MALZEME', 'YANGIN İTFAİYE BAĞLANTI AĞZI', 1181),
  ('MALZEME', 'YANGIN İTFAİYE VANASI (2-1/2)', 1182),
  ('MALZEME', 'YANGIN TÜPÜ - 6 KG', 1183),
  ('MALZEME', 'YASTIK', 1184),
  ('MALZEME', 'YASTIK SİLİKONLU BEYAZ', 1185),
  ('MALZEME', 'YATAK SÜNGERİ', 1186),
  ('MALZEME', 'YELEK', 1187),
  ('MALZEME', 'YELEK - CEPLİ', 1188),
  ('MALZEME', 'YELEK - KIRMIZI', 1189),
  ('MALZEME', 'YEMEK', 1190),
  ('MALZEME', 'YEMEK MASASI', 1191),
  ('MALZEME', 'YER YAPIŞTIRICISI - 4 KG', 1192),
  ('MALZEME', 'YEŞİL LAZER HİZALAMA - DEWALT DW088CG-XJ', 1193),
  ('MALZEME', 'YORGAN - BATTANİYE', 1194),
  ('MALZEME', 'YORGAN SİLİKONLU', 1195),
  ('MALZEME', 'YOYO - ÇELİK 10 MT', 1196),
  ('MALZEME', 'YOYO - ÇELİK 20 MT', 1197),
  ('MALZEME', 'ZIMPARA', 1198),
  ('MALZEME', 'ZIMPARA TAKOZU', 1199),
  ('MALZEME', 'ZİNCİR', 1200),
  ('MALZEME', 'ZİNCİR GALVANİZLİ - 8MM', 1201),
  ('MALZEME', 'ZİNCİR GALVANİZLİ 6 MM', 1202),
  ('MALZEME', 'МАТКАР UCU SDS PLUS 10x160', 1203),
  ('MALZEME', 'МАТКАР UCU SDS PLUS 12x160', 1204),
  ('MALZEME', 'МАТКАР UCU SDS PLUS 8x160', 1205),
  ('FATURA_KATEGORI', 'YEMEK', 0),
  ('FATURA_KATEGORI', 'NALBUR VE HIRDAVAT', 1),
  ('FATURA_KATEGORI', 'YAPI MALZEMESİ', 2),
  ('FATURA_KATEGORI', 'TESİSAT MALZEMESİ', 3),
  ('FATURA_KATEGORI', 'MARKET', 4),
  ('FATURA_KATEGORI', 'KIRTASİYE', 5),
  ('FATURA_KATEGORI', 'ARAÇ', 6),
  ('FATURA_KATEGORI', 'KONAKLAMA', 7),
  ('FATURA_KATEGORI', 'NAKLİYE', 8),
  ('FATURA_KATEGORI', 'KİRALAMA', 9),
  ('FATURA_KATEGORI', 'İŞÇİLİK', 10),
  ('ODEME', 'YENİ GİRİLDİ', 0),
  ('ODEME', 'BEKLEMEDE', 1),
  ('ODEME', 'ÖDEME LİSTESİNDE', 2),
  ('ODEME', 'KISMİ ÖDENDİ', 3),
  ('ODEME', 'ÖDEME YAPILDI', 4),
  ('ODEME', 'K.K. İLE ÖDEME YAPILDI', 5),
  ('ODEME', 'CARİ', 6),
  ('ODEME', 'FATURA İPTAL', 7)
ON CONFLICT ("grup", "deger") DO NOTHING;

-- Kullanıcılar (parola: degistir123)
INSERT INTO "Kullanici" ("ad", "eposta", "parolaHash", "rol") VALUES
  ('Yönetici', 'yonetici@sirket.com', '090df223eab09ba51107be0b6c905463:24f5836f0a9d43925b2214dda5f5396ca5c5c8493a3276209edeb0960eb26b37fa50717c8d6d7e5dd8d72229651039f46cd82b326739f361a216bfca1a696f7d', 'YONETICI'),
  ('Şantiye Kaydı', 'santiye@sirket.com', '96a749ebb6ed3fc3b9026d9aca50c829:ad7aa176d188c266cc0be9e0eaa5b9e16dd543e80d671d4a8481e2521c3c6a7058b41239b0832ecf914e9de9765a04c8e9031addf268f0890d39097694b6d0e7', 'SANTIYE'),
  ('İdari Müdür', 'idari@sirket.com', '619a85d4cdac535d553c5687713f05e3:64d4439ddce4e05a973a1bf16fa8f7b7d7dc8545c76af338cf02dd3e4f33072decd8d9da50ab4a1c4a96ca3efba9c08193f8a0780dc9e4e188c697aac871e6e4', 'IDARI_MUDUR'),
  ('Merkez Muhasebe', 'merkez@sirket.com', '5502723fdab66adbdd6610db70237679:19dcdfa07ed50fbac39abeb21e83a4645e7587bc3602412e7f32ab013ef7bb0360a5fe7a9ca723e641f7d25b59c35e4dbefe3d3fb08f024a9dc32d87cc756ede', 'MERKEZ')
ON CONFLICT ("eposta") DO NOTHING;

-- Ayarlar
INSERT INTO "Ayar" ("anahtar", "deger") VALUES
  ('sirket_adi', 'Şirket Adı'),
  ('santiye_adi', 'Şantiye'),
  ('musavir_adi', '')
ON CONFLICT ("anahtar") DO NOTHING;
